export type AssetKind = 'drawing' | 'illustration' | 'painting' | 'poster' | 'hidden' | 'collage' | 'tattoo'
export type AssetSize = `${number}x${number}`
export type Asset = {
    kind: AssetKind,
    name: string,
    title: string,
    year: number,
    material: string,
    size: AssetSize,
}
export const assets: Asset[] = [{
    kind: 'drawing',
    name: 'dog.png',
    title: 'Dog',
    year: 2022,
    material: 'ink on paper, color pencil',
    size: '1600x1200',
}, {
    kind: 'poster',
    name: 'in_bruges.png',
    title: 'In Bruges',
    year: 2022,
    material: 'gouache on paper, digital',
    size: '8268x118111',
}, {
    kind: 'poster',
    name: 'contra_spem_spero!.png',
    title: 'Contra spem spero!',
    year: 2022,
    material: 'digital',
    size: '8268x118111',
}, {
    kind: 'illustration',
    name: 'officer.png',
    title: 'Officer',
    year: 2022,
    material: 'digital',
    size: '1600x1200',
}, {
    kind: 'poster',
    name: '93rd.jpeg',
    title: '93rd',
    year: 2022,
    material: 'digital',
    size: '905x1280',
}, {
    kind: 'poster',
    name: 'aanda.jpeg',
    title: 'A&A',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'illustration',
    name: 'Anna.png',
    title: 'Anna',
    year: 2020,
    material: 'digital',
    size: '1600x1200',
}, {
    kind: 'poster',
    name: 'body.jpeg',
    title: 'Body',
    year: 2022,
    material: 'digital',
    size: '905x1280',
}, {
    kind: 'poster',
    name: 'bronx_gothic.jpeg',
    title: 'Bronx Gothic',
    year: 2022,
    material: 'colors pensil on paper, digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'darkside.jpeg',
    title: 'Darkside',
    year: 2022,
    material: 'digital',
    size: '896x1280',
}, {
    kind: 'poster',
    name: 'dont_talk.jpeg',
    title: 'Romance',
    year: 2022,
    material: 'diital',
    size: '853x1280',
}, {
    kind: 'painting',
    name: 'Flower_1.png',
    title: 'Flower 1',
    year: 2023,
    material: 'gouache on paper',
    size: '2433x2367',
}, {
    kind: 'painting',
    name: 'Flower_2.png',
    title: 'Flower 2',
    year: 2023,
    material: 'gouache on paper',
    size: '2433x2367',
}, {
    kind: 'painting',
    name: 'Flower_3.png',
    title: 'Flower 3',
    year: 2023,
    material: 'gouache on paper',
    size: '2433x2367',
}, {
    kind: 'painting',
    name: 'Flower_4.png',
    title: 'Flower 4',
    year: 2023,
    material: 'gouache on paper',
    size: '2433x2367',
}, {
    kind: 'painting',
    name: 'Flower_5.png',
    title: 'Flower 5',
    year: 2023,
    material: 'gouache on paper',
    size: '2433x2367',
}, {
    kind: 'painting',
    name: 'Flower_6.png',
    title: 'Flower 6',
    year: 2023,
    material: 'gouache on paper',
    size: '2433x2367',
}, {
    kind: 'painting',
    name: 'Flower_7.png',
    title: 'Flower 7',
    year: 2023,
    material: 'gouache on paper',
    size: '2433x2367',
}, {
    kind: 'painting',
    name: 'Flower_8.png',
    title: 'Flower 8',
    year: 2023,
    material: 'gouache on paper',
    size: '2433x2367',
}, {
    kind: 'painting',
    name: 'Flower_9.png',
    title: 'Flower 9',
    year: 2023,
    material: 'gouache on paper',
    size: '2433x2367',
}, {
    kind: 'illustration',
    name: 'frog.png',
    title: 'Frog',
    year: 2022,
    material: 'digital',
    size: '1600x1200',
}, {
    kind: 'poster',
    name: 'grand_spectacle_de_ballets.jpeg',
    title: 'Grand spectacle de ballets',
    year: 2022,
    material: 'digital',
    size: '896x1280',
}, {
    kind: 'illustration',
    name: 'greek_man.png',
    title: 'Greek man',
    year: 2019,
    material: 'digital',
    size: '896x1280',
}, {
    kind: 'poster',
    name: 'estata_la_mano_di_dio.JPG',
    title: 'Estata la mano di dio',
    year: 2022,
    material: 'digital',
    size: '896x1280',
}, {
    kind: 'illustration',
    name: 'eye.jpg',
    title: 'An eye',
    year: 2020,
    material: 'digital',
    size: '2048x2048',
}, {
    kind: 'illustration',
    name: 'happy.png',
    title: 'Happy',
    year: 2022,
    material: 'digital',
    size: '1600x1200',
}, {
    kind: 'illustration',
    name: 'look.jpg',
    title: 'Look',
    year: 2021,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'poster',
    name: 'in_decent.jpeg',
    title: 'In decent',
    year: 2022,
    material: 'ink on paper, digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'kyiv.png',
    title: 'Kyiv',
    year: 2022,
    material: 'mixed technique',
    size: '8268x11811',
}, {
    kind: 'poster',
    name: 'LA.jpeg',
    title: 'LA',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'LACMA_2.png',
    title: 'LACMA',
    year: 2022,
    material: 'digital',
    size: '8268x11811',
}, {
    kind: 'poster',
    name: 'les_miserables.jpeg',
    title: 'Les miserables',
    year: 2022,
    material: 'mixed technique',
    size: '896x1280',
}, {
    kind: 'poster',
    name: 'look.jpeg',
    title: 'Look through',
    year: 2022,
    material: 'digital',
    size: '896x1280',
}, {
    kind: 'poster',
    name: 'love.jpeg',
    title: 'LOVE',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'macbeth.jpeg',
    title: 'Macbeth',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'marshall.jpeg',
    title: 'Marshall',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'me.jpeg',
    title: 'Me',
    year: 2022,
    material: 'digital',
    size: '896x1280',
}, {
    kind: 'poster',
    name: 'monstres.jpeg',
    title: 'Monstres',
    year: 2022,
    material: 'mixed technique',
    size: '896x1280',
}, {
    kind: 'poster',
    name: 'oper.jpeg',
    title: 'Oper',
    year: 2022,
    material: 'mixed technique',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'ophelia.jpeg',
    title: 'Ophelia',
    year: 2022,
    material: 'mixed technique',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'RandJ.jpeg',
    title: 'R&J',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'Romeo_and_Juliet.jpeg',
    title: 'Romeo and Juliet',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'romeoandjuliet.jpeg',
    title: 'Romeo&Juliet',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'SPAM_1.jpeg',
    title: 'SPAM_1',
    year: 2022,
    material: 'marker on paper',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'SPAM_2.jpeg',
    title: 'SPAM_2',
    year: 2022,
    material: 'marker on paper',
    size: '853x1280',
}, {
    kind: 'illustration',
    name: 'pain.jpg',
    title: 'Pain',
    year: 2021,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'rabbit.jpg',
    title: 'Rabbit',
    year: 2020,
    material: 'digital',
    size: '2048x2048',
}, {
    kind: 'illustration',
    name: 'rose.jpg',
    title: 'Rose',
    year: 2023,
    material: 'digital',
    size: '2048x2048',
}, {
    kind: 'poster',
    name: 'shape.jpeg',
    title: 'Shape',
    year: 2022,
    material: 'digital',
    size: '905x1280',
}, {
    kind: 'poster',
    name: 'symbol.jpeg',
    title: 'Symbol',
    year: 2022,
    material: 'digital',
    size: '905x1280',
}, {
    kind: 'poster',
    name: 'the_hour_we_know_nothing.jpeg',
    title: 'The Hour',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'under_wave.jpeg',
    title: 'Under Wave',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'venice_beach.jpeg',
    title: 'Party',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'venice.jpeg',
    title: 'Venice',
    year: 2022,
    material: 'digital',
    size: '905x1280',
}, {
    kind: 'poster',
    name: 'w.jpeg',
    title: 'W',
    year: 2022,
    material: 'digital',
    size: '905x1280',
}, {
    kind: 'poster',
    name: 'war_peace.png',
    title: 'WAR\PEACE',
    year: 2022,
    material: 'digital',
    size: '8268x11811',
}, {
    kind: 'poster',
    name: 'war.jpeg',
    title: 'War',
    year: 2022,
    material: 'digital',
    size: '905x1280',
}, {
    kind: 'poster',
    name: 'when.jpeg',
    title: 'Vingranovsky',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'you.jpeg',
    title: 'YOU',
    year: 2022,
    material: 'digital',
    size: '896x1280',
}, {
    kind: 'illustration',
    name: 'walk.png',
    title: 'Walk',
    year: 2022,
    material: 'digital',
    size: '2644x2048',
}, {
    kind: 'illustration',
    name: 'anxiety_thoughts.png',
    title: 'Anxiety Thoughts',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'anxiety_1.png',
    title: 'Anxiety',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'Behavioral_Activation.png',
    title: 'Behavioral Activation',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'tattoo',
    name: 'bird_2.png',
    title: 'Bird',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'tattoo',
    name: 'bird.png',
    title: 'Bird',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'book.png',
    title: 'Book',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'bored.png',
    title: 'Bored',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'brain.png',
    title: 'Brain',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'candles.png',
    title: 'Candles',
    year: 2023,
    material: 'digital',
    size: '3024x4032',
}, {
    kind: 'collage',
    name: 'cinema_1.png',
    title: 'Cinema',
    year: 2023,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'collage',
    name: 'cinema_2.png',
    title: 'Cinema',
    year: 2023,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'collage',
    name: 'cinema_3.png',
    title: 'Cinema',
    year: 2023,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'collage',
    name: 'cinema_4.png',
    title: 'Cinema',
    year: 2023,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'illustration',
    name: 'clock.png',
    title: 'Clock',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'Cognitive_Restructuring.png',
    title: 'Cognitive Restructuring',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'diarrhea.png',
    title: 'Diarrhea',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'dream.png',
    title: 'Dream',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'Exposure_Therapy.png',
    title: 'Exposure Therapy',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'falling.png',
    title: 'Falling',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'eye.png',
    title: 'Eye',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'feel_good_1.png',
    title: 'Feel good',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'Five_Senses_Grounding_Technique.png',
    title: 'Five senses grounding technique',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'fixed.png',
    title: 'Fixed',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'forty_million.png',
    title: 'Forty million',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'gift.png',
    title: 'Gift',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'headache.png',
    title: 'Headache',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'collage',
    name: 'history_1.png',
    title: 'History',
    year: 2023,
    material: 'digital',
    size: '963x729',
}, {
    kind: 'illustration',
    name: 'line.png',
    title: 'Line',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'lion.png',
    title: 'Lion',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'love.png',
    title: 'Love',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'man.png',
    title: 'Man',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'poster',
    name: 'mano.png',
    title: 'Estata la mano di Dio',
    year: 2022,
    material: 'digital',
    size: '8268x11811',
}, {
    kind: 'illustration',
    name: 'mess.png',
    title: 'Mess',
    year: 2022,
    material: 'digital',
    size: '2500x2500',
}, {
    kind: 'illustration',
    name: 'Mindful_Eating.png',
    title: 'Mindful eating',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'Mindful_Handwashing.png',
    title: 'Minful handwashing',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'mood.png',
    title: 'Mood',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'moon.png',
    title: 'Moon',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'collage',
    name: 'music_2.png',
    title: 'Music',
    year: 2022,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'collage',
    name: 'music_3_2.png',
    title: 'Music',
    year: 2022,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'collage',
    name: 'music_4_2.png',
    title: 'Music',
    year: 2022,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'collage',
    name: 'music_5.png',
    title: 'Music',
    year: 2022,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'illustration',
    name: 'namaste.png',
    title: 'Namaste',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'phone.png',
    title: 'Phone',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'pigeon.JPG',
    title: 'Pigeon',
    year: 2022,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'pill.png',
    title: 'Pill',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'pleasant_time.png',
    title: 'Time',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'Problem-Solving_Technique.png',
    title: 'Problem solving technique',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'RAIN_Technique.png',
    title: 'RAIN',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'reminder.png',
    title: 'Reminder',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'routine.png',
    title: 'Routine',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'Self-Monitoring.png',
    title: 'Self Monitoring',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'sleep.png',
    title: 'Sleep',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'smell.png',
    title: 'Smell',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'snakes.png',
    title: 'Snakes',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'star_brain.png',
    title: 'Brain',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'star.png',
    title: 'Star',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'stress_1.png',
    title: 'Stress',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'stress.png',
    title: 'Stress',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'summer.png',
    title: 'Summer',
    year: 2022,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'tattoo',
    name: 'sun.png',
    title: 'Sun',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'support.png',
    title: 'Support',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'sweet_dream.png',
    title: 'Sweet',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'thoghts.png',
    title: 'Thoghts',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'Thought_Records.png',
    title: 'Thought records',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'together.png',
    title: 'Together',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'tooth.png',
    title: 'Tooth',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'collage',
    name: 'ukraine_history_1.png',
    title: 'Ukraine history',
    year: 2022,
    material: 'digital',
    size: '962x729',
}, {
    kind: 'collage',
    name: 'ukraine_history_2.jpg',
    title: 'Ukraine history',
    year: 2022,
    material: 'digital',
    size: '962x729',
}, {
    kind: 'collage',
    name: 'ukraine_history_3.png',
    title: 'Ukraine history',
    year: 2022,
    material: 'digital',
    size: '460x535',
}, {
    kind: 'collage',
    name: 'ukraine_history_4.png',
    title: 'Ukraine history',
    year: 2022,
    material: 'digital',
    size: '542x1230',
}, {
    kind: 'collage',
    name: 'ukraine_history_5.jpg',
    title: 'Ukraine history',
    year: 2022,
    material: 'digital',
    size: '542x1230',
}, {
    kind: 'collage',
    name: 'ukraine_history_6.jpg',
    title: 'Ukraine history',
    year: 2022,
    material: 'digital',
    size: '460x535',
}, {
    kind: 'illustration',
    name: 'Walking_Meditation.PNG',
    title: 'Walking meditation',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'collage',
    name: '10_grn.jpg',
    title: '10 hryvnias',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'all_cats.jpg',
    title: 'All cats',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'au_revoir_mon_cher.jpg',
    title: 'Au revoir,moncher.jpg',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1925',
}, {
    kind: 'collage',
    name: 'deep.jpg',
    title: 'Deep',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'find_real_job.jpg',
    title: 'Are you looking for real job?',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1461',
}, {
    kind: 'collage',
    name: 'hat.jpg',
    title: 'Hat',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1925',
}, {
    kind: 'collage',
    name: 'have_a_good_one.jpg',
    title: 'Have a good one!',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'is_your_red.jpg',
    title: 'Is your red the same red as mine?',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1925',
}, {
    kind: 'collage',
    name: 'just_dont_do_it.jpg',
    title: "Just don't do it",
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1277x1314',
}, {
    kind: 'collage',
    name: 'king.jpg',
    title: 'King',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'latte.jpg',
    title: 'lAtte-lattE',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1246x1388',
}, {
    kind: 'collage',
    name: 'look_at_her.jpg',
    title: 'Look at her!',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'mcdonalds.jpg',
    title: "McDonald's",
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'not_so_premium.jpg',
    title: 'Not so premium!',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'Peacedove.jpg',
    title: 'Peacedove',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'photo.jpg',
    title: 'Photo',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1925',
}, {
    kind: 'collage',
    name: 'Ryaba_Hen.jpg',
    title: 'Ryaba Hen',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'stop.jpg',
    title: 'STOP',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1682',
}, {
    kind: 'collage',
    name: 'the_human_face.jpg',
    title: 'The human face',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'have_a_good_one.jpg',
    title: 'Have a Good One!',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'Treasure.jpg',
    title: 'Treasure',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1540',
}, {
    kind: 'collage',
    name: 'what.jpg',
    title: 'What',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1925',
}, {
    kind: 'collage',
    name: 'working_hard.jpg',
    title: 'Working Hard',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1925',
}, {
    kind: 'collage',
    name: 'We_are_getting_off_at_the_next_stop.jpg',
    title: 'We Are Getting Off At The Next Stop',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1879',
}]