export type AssetKind = 'drawing' | 'illustration' | 'painting' | 'poster' | 'hidden' | 'collage' | 'tattoo'
export type AssetSize = `${number}x${number}`
export type Asset = {
    kind: AssetKind,
    name: string,
    title: string,
    year: number,
    material: string,
    size: AssetSize,
}

export function assetsForKind(assets: Asset[], kind: AssetKind) {
    return assets.filter((asset) => asset.kind === kind)
}
export function assetSrc(asset: Asset) {
    return `/${asset.name}`
}
export function assetAlt(asset: Asset) {
    return `${asset.title} (${asset.year})`
}
export function assetWidth(asset: Asset) {
    return asset.size ? parseInt(asset.size.split('x')[0]) : 300
}
export function assetHeight(asset: Asset) {
    return asset.size ? parseInt(asset.size.split('x')[1]) : 300
}
export function assetDescription(asset: Asset) {
    return `${asset.title} (${asset.year}), ${asset.material}`
}
export function assetHref(asset: Asset) {
    return `/works/${assetSegment(asset)}`
}
export function assetSegment(asset: Asset) {
    return asset.title.toLowerCase().replace(/[^a-zA-Z0-9]/g, '-')
}
export function findAssetForSegment(assets: Asset[], segment: string) {
    return assets.find((asset) => assetSegment(asset) === segment)
}
export const assets: Asset[] = [{
    kind: 'drawing',
    name: 'dog.png',
    title: 'Dog',
    year: 2022,
    material: 'ink on paper, color pencil',
    size: '1600x1200',
}, {
    kind: 'poster',
    name: 'in_bruges.png',
    title: 'In Bruges',
    year: 2022,
    material: 'gouache on paper, digital',
    size: '8268x11811',
}, {
    kind: 'poster',
    name: 'contra_spem_spero!.png',
    title: 'Contra spem spero!',
    year: 2022,
    material: 'digital',
    size: '8268x11811',
}, {
    kind: 'illustration',
    name: 'officer.png',
    title: 'Officer',
    year: 2022,
    material: 'digital',
    size: '1600x1200',
}, {
    kind: 'poster',
    name: '93rd.jpeg',
    title: '93rd',
    year: 2022,
    material: 'digital',
    size: '905x1280',
}, {
    kind: 'poster',
    name: 'aanda.jpeg',
    title: 'A&A',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'illustration',
    name: 'Anna.png',
    title: 'Anna',
    year: 2020,
    material: 'digital',
    size: '1600x1200',
}, {
    kind: 'poster',
    name: 'body.jpeg',
    title: 'Body',
    year: 2022,
    material: 'digital',
    size: '905x1280',
}, {
    kind: 'poster',
    name: 'bronx_gothic.jpeg',
    title: 'Bronx Gothic',
    year: 2022,
    material: 'colors pensil on paper, digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'darkside.jpeg',
    title: 'Darkside',
    year: 2022,
    material: 'digital',
    size: '896x1280',
}, {
    kind: 'poster',
    name: 'dont_talk.jpeg',
    title: 'Romance',
    year: 2022,
    material: 'diital',
    size: '853x1280',
}, {
    kind: 'painting',
    name: 'Flower_1.png',
    title: 'Flower 1',
    year: 2023,
    material: 'gouache on paper',
    size: '2433x2367',
}, {
    kind: 'painting',
    name: 'Flower_2.png',
    title: 'Flower 2',
    year: 2023,
    material: 'gouache on paper',
    size: '2433x2367',
}, {
    kind: 'painting',
    name: 'Flower_3.png',
    title: 'Flower 3',
    year: 2023,
    material: 'gouache on paper',
    size: '2433x2367',
}, {
    kind: 'painting',
    name: 'Flower_4.png',
    title: 'Flower 4',
    year: 2023,
    material: 'gouache on paper',
    size: '2433x2367',
}, {
    kind: 'painting',
    name: 'Flower_5.png',
    title: 'Flower 5',
    year: 2023,
    material: 'gouache on paper',
    size: '2433x2367',
}, {
    kind: 'painting',
    name: 'Flower_6.png',
    title: 'Flower 6',
    year: 2023,
    material: 'gouache on paper',
    size: '2433x2367',
}, {
    kind: 'painting',
    name: 'Flower_7.png',
    title: 'Flower 7',
    year: 2023,
    material: 'gouache on paper',
    size: '2433x2367',
}, {
    kind: 'painting',
    name: 'Flower_8.png',
    title: 'Flower 8',
    year: 2023,
    material: 'gouache on paper',
    size: '2433x2367',
}, {
    kind: 'painting',
    name: 'Flower_9.png',
    title: 'Flower 9',
    year: 2023,
    material: 'gouache on paper',
    size: '2433x2367',
}, {
    kind: 'illustration',
    name: 'frog.png',
    title: 'Frog',
    year: 2022,
    material: 'digital',
    size: '1600x1200',
}, {
    kind: 'poster',
    name: 'grand_spectacle_de_ballets.jpeg',
    title: 'Grand spectacle de ballets',
    year: 2022,
    material: 'digital',
    size: '896x1280',
}, {
    kind: 'illustration',
    name: 'greek_man.png',
    title: 'Greek man',
    year: 2019,
    material: 'digital',
    size: '896x1280',
}, {
    kind: 'poster',
    name: 'estata_la_mano_di_dio.JPG',
    title: 'Estata la mano di dio',
    year: 2022,
    material: 'digital',
    size: '896x1280',
}, {
    kind: 'illustration',
    name: 'eye.jpg',
    title: 'An eye',
    year: 2020,
    material: 'digital',
    size: '2048x2048',
}, {
    kind: 'illustration',
    name: 'happy.png',
    title: 'Happy',
    year: 2022,
    material: 'digital',
    size: '1600x1200',
}, {
    kind: 'illustration',
    name: 'look.jpg',
    title: 'Look',
    year: 2021,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'poster',
    name: 'in_decent.jpeg',
    title: 'In decent',
    year: 2022,
    material: 'ink on paper, digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'kyiv.png',
    title: 'Kyiv',
    year: 2022,
    material: 'mixed technique',
    size: '8268x11811',
}, {
    kind: 'poster',
    name: 'LA.jpeg',
    title: 'LA',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'LACMA_2.png',
    title: 'LACMA',
    year: 2022,
    material: 'digital',
    size: '8268x11811',
}, {
    kind: 'poster',
    name: 'les_miserables.jpeg',
    title: 'Les miserables',
    year: 2022,
    material: 'mixed technique',
    size: '896x1280',
}, {
    kind: 'poster',
    name: 'look.jpeg',
    title: 'Look through',
    year: 2022,
    material: 'digital',
    size: '896x1280',
}, {
    kind: 'poster',
    name: 'love.jpeg',
    title: 'Love (poster)',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'macbeth.jpeg',
    title: 'Macbeth',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'marshall.jpeg',
    title: 'Marshall',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'me.jpeg',
    title: 'Me',
    year: 2022,
    material: 'digital',
    size: '896x1280',
}, {
    kind: 'poster',
    name: 'monstres.jpeg',
    title: 'Monstres',
    year: 2022,
    material: 'mixed technique',
    size: '896x1280',
}, {
    kind: 'poster',
    name: 'oper.jpeg',
    title: 'Oper',
    year: 2022,
    material: 'mixed technique',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'ophelia.jpeg',
    title: 'Ophelia',
    year: 2022,
    material: 'mixed technique',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'RandJ.jpeg',
    title: 'R&J',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'Romeo_and_Juliet.jpeg',
    title: 'Romeo and Juliet',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'romeoandjuliet.jpeg',
    title: 'Romeo&Juliet',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'SPAM_1.jpeg',
    title: 'SPAM_1',
    year: 2022,
    material: 'marker on paper',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'SPAM_2.jpeg',
    title: 'SPAM_2',
    year: 2022,
    material: 'marker on paper',
    size: '853x1280',
}, {
    kind: 'illustration',
    name: 'pain.jpg',
    title: 'Pain',
    year: 2021,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'rabbit.jpg',
    title: 'Rabbit',
    year: 2020,
    material: 'digital',
    size: '2048x2048',
}, {
    kind: 'illustration',
    name: 'rose.jpg',
    title: 'Rose',
    year: 2023,
    material: 'digital',
    size: '2048x2048',
}, {
    kind: 'poster',
    name: 'shape.jpeg',
    title: 'Shape',
    year: 2022,
    material: 'digital',
    size: '905x1280',
}, {
    kind: 'poster',
    name: 'symbol.jpeg',
    title: 'Symbol',
    year: 2022,
    material: 'digital',
    size: '905x1280',
}, {
    kind: 'poster',
    name: 'the_hour_we_know_nothing.jpeg',
    title: 'The Hour',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'under_wave.jpeg',
    title: 'Under Wave',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'venice_beach.jpeg',
    title: 'Party',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'venice.jpeg',
    title: 'Venice',
    year: 2022,
    material: 'digital',
    size: '905x1280',
}, {
    kind: 'poster',
    name: 'w.jpeg',
    title: 'W',
    year: 2022,
    material: 'digital',
    size: '905x1280',
}, {
    kind: 'poster',
    name: 'war_peace.png',
    title: 'WAR\PEACE',
    year: 2022,
    material: 'digital',
    size: '8268x11811',
}, {
    kind: 'poster',
    name: 'war.jpeg',
    title: 'War',
    year: 2022,
    material: 'digital',
    size: '905x1280',
}, {
    kind: 'poster',
    name: 'when.jpeg',
    title: 'Vingranovsky',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'you.jpeg',
    title: 'YOU',
    year: 2022,
    material: 'digital',
    size: '896x1280',
}, {
    kind: 'illustration',
    name: 'walk.png',
    title: 'Walk',
    year: 2022,
    material: 'digital',
    size: '2644x2048',
}, {
    kind: 'illustration',
    name: 'anxiety_thoughts.png',
    title: 'Anxiety Thoughts',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'anxiety_1.png',
    title: 'Anxiety',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'Behavioral_Activation.png',
    title: 'Behavioral Activation',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'tattoo',
    name: 'bird_2.png',
    title: 'Bird #2',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'tattoo',
    name: 'bird.png',
    title: 'Bird',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'book.png',
    title: 'Book',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'bored.png',
    title: 'Bored',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'brain.png',
    title: 'Brain',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'candles.png',
    title: 'Candles',
    year: 2023,
    material: 'digital',
    size: '3024x4032',
}, {
    kind: 'collage',
    name: 'cinema_1.png',
    title: 'Cinema #1',
    year: 2023,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'collage',
    name: 'cinema_2.png',
    title: 'Cinema #2',
    year: 2023,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'collage',
    name: 'cinema_3.png',
    title: 'Cinema #3',
    year: 2023,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'collage',
    name: 'cinema_4.png',
    title: 'Cinema #4',
    year: 2023,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'illustration',
    name: 'clock.png',
    title: 'Clock',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'Cognitive_Restructuring.png',
    title: 'Cognitive Restructuring',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'diarrhea.png',
    title: 'Diarrhea',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'dream.png',
    title: 'Dream',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'Exposure_Therapy.png',
    title: 'Exposure Therapy',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'falling.png',
    title: 'Falling',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'eye.png',
    title: 'Eye',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'feel_good_1.png',
    title: 'Feel good',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'Five_Senses_Grounding_Technique.png',
    title: 'Five senses grounding technique',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'fixed.png',
    title: 'Fixed',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'forty_million.png',
    title: 'Forty million',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'gift.png',
    title: 'Gift',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'headache.png',
    title: 'Headache',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'collage',
    name: 'history_1.png',
    title: 'History',
    year: 2023,
    material: 'digital',
    size: '963x729',
}, {
    kind: 'illustration',
    name: 'line.png',
    title: 'Line',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'lion.png',
    title: 'Lion',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'love.png',
    title: 'Love',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'man.png',
    title: 'Man',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'mess.png',
    title: 'Mess',
    year: 2022,
    material: 'digital',
    size: '2500x2500',
}, {
    kind: 'illustration',
    name: 'Mindful_Eating.png',
    title: 'Mindful eating',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'Mindful_Handwashing.png',
    title: 'Minful handwashing',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'mood.png',
    title: 'Mood',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'moon.png',
    title: 'Moon',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'collage',
    name: 'music_2.png',
    title: 'Music #1',
    year: 2022,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'collage',
    name: 'music_3_2.png',
    title: 'Music #2',
    year: 2022,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'collage',
    name: 'music_4_2.png',
    title: 'Music #3',
    year: 2022,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'collage',
    name: 'music_5.png',
    title: 'Music #4',
    year: 2022,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'illustration',
    name: 'namaste.png',
    title: 'Namaste',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'phone.png',
    title: 'Phone',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'pigeon.JPG',
    title: 'Pigeon',
    year: 2022,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'pill.png',
    title: 'Pill',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'pleasant_time.png',
    title: 'Time',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'Problem-Solving_Technique.png',
    title: 'Problem solving technique',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'RAIN_Technique.png',
    title: 'RAIN',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'reminder.png',
    title: 'Reminder',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'routine.png',
    title: 'Routine',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'Self-Monitoring.png',
    title: 'Self Monitoring',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'sleep.png',
    title: 'Sleep',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'smell.png',
    title: 'Smell',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'snakes.png',
    title: 'Snakes',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'star_brain.png',
    title: 'Star Brain',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'star.png',
    title: 'Star',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'stress_1.png',
    title: 'Stress #1',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'stress_2.png',
    title: 'Stress #2',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'summer.png',
    title: 'Summer',
    year: 2022,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'tattoo',
    name: 'sun.png',
    title: 'Sun',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'support.png',
    title: 'Support',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'sweet_dream.png',
    title: 'Sweet',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'thoghts.png',
    title: 'Thoghts',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'Thought_Records.png',
    title: 'Thought records',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'together.png',
    title: 'Together',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'tooth.png',
    title: 'Tooth',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'collage',
    name: 'ukraine_history_1.png',
    title: 'Ukrainian History #1',
    year: 2022,
    material: 'digital',
    size: '962x729',
}, {
    kind: 'collage',
    name: 'ukraine_history_2.jpg',
    title: 'Ukrainian History #2',
    year: 2022,
    material: 'digital',
    size: '962x729',
}, {
    kind: 'collage',
    name: 'ukraine_history_3.png',
    title: 'Ukrainian History #3',
    year: 2022,
    material: 'digital',
    size: '460x535',
}, {
    kind: 'collage',
    name: 'ukraine_history_4.png',
    title: 'Ukrainian History #4',
    year: 2022,
    material: 'digital',
    size: '542x1230',
}, {
    kind: 'collage',
    name: 'ukraine_history_5.jpg',
    title: 'Ukrainian History #5',
    year: 2022,
    material: 'digital',
    size: '542x1230',
}, {
    kind: 'collage',
    name: 'ukraine_history_6.jpg',
    title: 'Ukrainian History #6',
    year: 2022,
    material: 'digital',
    size: '460x535',
}, {
    kind: 'illustration',
    name: 'Walking_Meditation.PNG',
    title: 'Walking Meditation',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'collage',
    name: '10_hrn.jpg',
    title: '10 Hryvnias',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'all_cats.jpg',
    title: 'All Cats',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'au_revoir_mon_cher.jpg',
    title: 'Au revoir,moncher.jpg',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1925',
}, {
    kind: 'collage',
    name: 'deep.jpg',
    title: 'Deep',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'find_real_job.jpg',
    title: 'Are you looking for real job?',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1461',
}, {
    kind: 'collage',
    name: 'hat.jpg',
    title: 'Hat',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1925',
}, {
    kind: 'collage',
    name: 'is_your_red.jpg',
    title: 'Is your red the same red as mine?',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1925',
}, {
    kind: 'collage',
    name: 'just_dont_do_it.jpg',
    title: "Just don't do it",
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1277x1314',
}, {
    kind: 'collage',
    name: 'king.jpg',
    title: 'King',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'latte.jpg',
    title: 'lAtte-lattE',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1246x1388',
}, {
    kind: 'collage',
    name: 'look_at_her.jpg',
    title: 'Look at her!',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'mcdonalds.jpg',
    title: "McDonald's",
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'not_so_premium.jpg',
    title: 'Not so premium!',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'Peacedove.jpg',
    title: 'Peacedove',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'photo.jpg',
    title: 'Photo',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1925',
}, {
    kind: 'collage',
    name: 'Ryaba_Hen.jpg',
    title: 'Ryaba Hen',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'stop.jpg',
    title: 'STOP',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1682',
}, {
    kind: 'collage',
    name: 'the_human_face.jpg',
    title: 'The human face',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'have_a_good_one.jpg',
    title: 'Have a Good One!',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'Treasure.jpg',
    title: 'Treasure',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1540',
}, {
    kind: 'collage',
    name: 'what.jpg',
    title: 'What',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1925',
}, {
    kind: 'collage',
    name: 'working_hard.jpg',
    title: 'Working Hard',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1925',
}, {
    kind: 'collage',
    name: 'We_are_getting_off_at_the_next_stop.jpg',
    title: 'We Are Getting Off At The Next Stop',
    year: 2015,
    material: 'paper cuttings, ink',
    size: '1400x1879',
}, {
    kind: 'painting',
    name: 'tiger_on_green.jpg',
    title: 'Tiger On Green',
    year: 2021,
    material: 'ink and gouche on paper',
    size: '872x1240',
}, {
    kind: 'painting',
    name: 'after_illness_selfportrait_color.png',
    title: 'After Illness Selfportrait Color.png',
    year: 2023,
    material: 'gouache on paper',
    size: '2386x339',
}, {
    kind: 'painting',
    name: 'after_illness_selfportrait_dark.png',
    title: 'After Illness Selfportrait Dark',
    year: 2023,
    material: 'gouache on paper',
    size: '2228x3078',
}, {
    kind: 'illustration',
    name: 'antiseptic.JPG',
    title: 'antiseptic',
    year: 2019,
    material: 'digital',
    size: '2000x1495',
}, {
    kind: 'painting',
    name: 'Anton.png',
    title: 'Anton',
    year: 2022,
    material: 'acrylic on paper',
    size: '2568x3504',
}, {
    kind: 'tattoo',
    name: 'Antons_tiger.png',
    title: 'Antons Tiger',
    year: 2022,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'drawing',
    name: 'beach.jpg',
    title: 'Beach',
    year: 2022,
    material: 'marker on paper',
    size: '680x1257',
}, {
    kind: 'drawing',
    name: 'Berlin_museum.JPG',
    title: 'Berlin Museum',
    year: 2022,
    material: 'pensils on paper',
    size: '2767x2767',
}, {
    kind: 'illustration',
    name: 'bite_snake.PNG',
    title: 'Snake bite',
    year: 2022,
    material: 'digital',
    size: '2048x2048',
}, {
    kind: 'drawing',
    name: 'blue_man.png',
    title: 'Blue Man',
    year: 2021,
    material: 'ink on paper',
    size: '3122x2206',
}, {
    kind: 'drawing',
    name: 'Bucha.JPG',
    title: 'Bucha',
    year: 2022,
    material: 'ink on paper',
    size: '1440x1017',
}, {
    kind: 'illustration',
    name: 'cat_sitting.JPG',
    title: 'Cat Sitting',
    year: 2019,
    material: 'digital',
    size: '1679x1667',
}, {
    kind: 'drawing',
    name: 'daisies.png',
    title: 'Daisies',
    year: 2022,
    material: 'ink and pensil on paper',
    size: '4032x3024',
}, {
    kind: 'painting',
    name: 'Daryn.png',
    title: 'Daryn',
    year: 2023,
    material: 'acrylic on paper',
    size: '1795x2723',
}, {
    kind: 'illustration',
    name: 'dead_dragon.PNG',
    title: 'Dead Dragon',
    year: 2022,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'drawing',
    name: 'elephant.JPG',
    title: 'Elephant',
    year: 2022,
    material: 'ink on paper',
    size: '1440x1777',
}, {
    kind: 'painting',
    name: 'first_working_day_selfportrait.JPG',
    title: 'First Working Day Selfportrait',
    year: 2022,
    material: 'acrylic on paper',
    size: '1212x1176',
}, {
    kind: 'drawing',
    name: 'Gogen_girl.jpg',
    title: 'Gogen Girl',
    year: 2022,
    material: 'pencils on paper',
    size: '2889x2889',
}, {
    kind: 'drawing',
    name: 'happy_flower.jpg',
    title: 'Happy Flower',
    year: 2022,
    material: 'ink and pencil on paper',
    size: '2037x2791',
}, {
    kind: 'illustration',
    name: 'i_live_in_Berlin.JPG',
    title: 'I Live In Berlin',
    year: 2022,
    material: 'digital',
    size: '2048x2048',
}, {
    kind: 'illustration',
    name: 'insomnia.JPG',
    title: 'Insomnia',
    year: 2020,
    material: 'digital',
    size: '2048x2048',
}, {
    kind: 'painting',
    name: 'lemon_tree.png',
    title: 'Lemon Tree',
    year: 2022,
    material: 'acrylic on canvas',
    size: '1422x2176',
}, {
    kind: 'drawing',
    name: 'light_flower.png',
    title: 'Light Flower',
    year: 2023,
    material: 'pastel on paper',
    size: '1991x2468',
}, {
    kind: 'illustration',
    name: 'looking_for.JPG',
    title: 'Looking For',
    year: 2021,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'drawing',
    name: 'lying_down_woman.jpg',
    title: 'Lying Down Woman',
    year: 2021,
    material: 'ink and pastel on paper',
    size: '1215x875',
}, {
    kind: 'tattoo',
    name: 'match.png',
    title: 'Match',
    year: 2022,
    material: 'hand poke',
    size: '2498x3478',
}, {
    kind: 'illustration',
    name: 'micro_green.JPG',
    title: 'Microgreen',
    year: 2020,
    material: 'digital',
    size: '2500x1500',
}, {
    kind: 'painting',
    name: 'mountain_bouquet.png',
    title: 'Mountain Bouquet',
    year: 2023,
    material: 'acrylic on canvas',
    size: '2640x3464',
}, {
    kind: 'illustration',
    name: 'my_city.PNG',
    title: 'My City',
    year: 2022,
    material: 'digital',
    size: '1668x1995',
}, {
    kind: 'illustration',
    name: 'need_hugs.JPG',
    title: 'Need Hugs',
    year: 2020,
    material: 'digital',
    size: '2048x2048',
}, {
    kind: 'drawing',
    name: 'nervous_self_portrait.JPG',
    title: 'Nervous Self Portrait',
    year: 2023,
    material: 'charcoal on paper',
    size: '1829x2569',
}, {
    kind: 'drawing',
    name: 'parrot.png',
    title: 'Parrot',
    year: 2022,
    material: 'ink on paper',
    size: '3275x2342',
}, {
    kind: 'tattoo',
    name: 'pin_pong.JPG',
    title: 'Pin-Pong',
    year: 2023,
    material: 'hand poke',
    size: '1440x1800',
}, {
    kind: 'drawing',
    name: 'premonition_of_war.png',
    title: 'Premonition of War',
    year: 2022,
    material: 'ink on paper',
    size: '2809x1979',
}, {
    kind: 'tattoo',
    name: 'prickly_flower.png',
    title: 'Prickly Flower',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'painting',
    name: 'red_flower.png',
    title: 'Red Flower',
    year: 2023,
    material: 'gouache on paper',
    size: '2437x3048',
}, {
    kind: 'illustration',
    name: 'red_hat_lady.PNG',
    title: 'Red Hat Lady.PNG',
    year: 2023,
    material: 'digital',
    size: '2048x2048',
}, {
    kind: 'tattoo',
    name: 'red_ornament.png',
    title: 'Red Ornament',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'drawing',
    name: 'running_away.JPG',
    title: 'Running Away',
    year: 2022,
    material: 'ink and pensil on paper',
    size: '1440x999',
}, {
    kind: 'drawing',
    name: 'sad_evening.png',
    title: 'Sad Evening',
    year: 2023,
    material: 'marker on paper',
    size: '2379x3197',
}, {
    kind: 'drawing',
    name: 'sad_selfportrait.PNG',
    title: 'Sad Selfportrait',
    year: 2022,
    material: 'charcoal on paper',
    size: '2890x2268',
}, {
    kind: 'painting',
    name: 'self_portrait_color.jpg',
    title: 'Self Portrait in Color',
    year: 2023,
    material: 'acrylic on paper',
    size: '1984x3115',
}, {
    kind: 'illustration',
    name: 'self_portrait_on_a_chair.JPG',
    title: 'Self Portrait on A Chair',
    year: 2020,
    material: 'digital',
    size: '2048x2048',
}, {

    kind: 'drawing',
    name: 'shark_girl.JPG',
    title: 'Shark Girl',
    year: 2022,
    material: 'ink on paper',
    size: '2391x2988',
}, {
    kind: 'drawing',
    name: 'SPAM_cane.JPG',
    title: 'SPAM Cane',
    year: 2022,
    material: 'pencils on paper',
    size: '3024x3024',
}, {
    kind: 'illustration',
    name: 'stand_with_ukraine.PNG',
    title: 'Stand With Ukraine',
    year: 2022,
    material: 'digital',
    size: '2048x2048',
}, {
    kind: 'tattoo',
    name: 'star_collector.png',
    title: 'Star Collector',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'tattoo',
    name: 'star_in_glasses.png',
    title: 'Star in Glasses',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'painting',
    name: 'sunscreen_selfportrait.png',
    title: 'Sunscreen Selfportrait',
    year: 2022,
    material: 'acrylic on paper',
    size: '2262x2321',
}, {
    kind: 'painting',
    name: 'The_Color_of_Pomegranates.png',
    title: 'The Color of Pomegranates',
    year: 2022,
    material: 'acrylic on paper',
    size: '2395x2841',
}, {
    kind: 'painting',
    name: 'tiger_on_green_with_dots.jpg',
    title: 'Tiger on Green With Dots',
    year: 2021,
    material: 'ink on paper',
    size: '872x1240',
}, {
    kind: 'painting',
    name: 'tiger_on_light_green.jpg',
    title: 'Tiger on Light Green',
    year: 2021,
    material: 'ink on paper',
    size: '843x1203',
}, {
    kind: 'painting',
    name: 'tiger_on_peace.jpg',
    title: 'Tiger on Peas',
    year: 2021,
    material: 'ink on paper',
    size: '850x1204',
}, {
    kind: 'painting',
    name: 'tiger_on_pink.jpg',
    title: 'Tiger on Pink',
    year: 2021,
    material: 'ink on paper',
    size: '930x1330',
}, {
    kind: 'painting',
    name: 'tiger_on_rose.jpg',
    title: 'Tiger on Rose',
    year: 2021,
    material: 'ink on paper',
    size: '897x1283',
}, {
    kind: 'painting',
    name: 'tiger_on_snow.jpg',
    title: 'Tiger on Snow',
    year: 2021,
    material: 'ink on paper',
    size: '854x1238',
}, {
    kind: 'painting',
    name: 'tiger_on_white.jpg',
    title: 'Tiger on White',
    year: 2021,
    material: 'ink on paper',
    size: '901x1287',
}, {
    kind: 'painting',
    name: 'tiger_on_yellow.jpg',
    title: 'Tiger on Yellow',
    year: 2021,
    material: 'ink on paper',
    size: '864x1249',
}, {
    kind: 'painting',
    name: 'tiger_with_lines.jpg',
    title: 'Tiger With Lines',
    year: 2021,
    material: 'ink on paper',
    size: '892x1264',
}, {
    kind: 'illustration',
    name: 'Valik.JPG',
    title: 'Valik',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'tattoo',
    name: 'venice_building.JPG',
    title: 'Venice Building',
    year: 2023,
    material: 'hand_poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'violet_dog.JPG',
    title: 'Violet Dog',
    year: 2021,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'drawing',
    name: 'walking_figure.jpg',
    title: 'Walking Figure',
    year: 2022,
    material: 'ink on paper',
    size: '1806x2580',
}, {
    kind: 'drawing',
    name: 'war_1.png',
    title: 'War 1',
    year: 2022,
    material: 'ink on paper',
    size: '2819x2152',
}, {
    kind: 'drawing',
    name: 'war_2.png',
    title: 'War 2',
    year: 2022,
    material: 'ink on paper',
    size: '3040x2352',
}, {
    kind: 'drawing',
    name: 'war_3.png',
    title: 'War 3',
    year: 2022,
    material: 'ink on paper',
    size: '2935x2182',
}, {
    kind: 'drawing',
    name: 'war_4.png',
    title: 'War 4',
    year: 2022,
    material: 'ink on paper',
    size: '2991x2260',
}, {
    kind: 'painting',
    name: 'wine.png',
    title: 'Wine',
    year: 2023,
    material: 'gouache on paper',
    size: '2278x2925',
}, {
    kind: 'drawing',
    name: 'woman_sculp.JPG',
    title: 'Woman Sculp',
    year: 2022,
    material: 'ink on paper',
    size: '1834x2293'
}]