import { AssetMetadata, generateAssetId } from "./assets"

export function getAssetMetadataForSeed(): AssetMetadata[] {
    return allAssets.map((asset) => convertLegacyAsset(asset))
}

type LegacyAssetKind = 'drawing' | 'illustration' | 'painting' | 'poster' | 'hidden' | 'collage' | 'tattoo'
type LegacyAssetTag = 'selfportrait' | 'favorite' | 'secondary'
type LegacyAssetSize = `${number}x${number}`
type LegacyAsset = {
    kind: LegacyAssetKind,
    name: string,
    title: string,
    year: number,
    material: string,
    size: LegacyAssetSize,
    tags?: LegacyAssetTag[],
}

function convertLegacyAsset(asset: LegacyAsset): AssetMetadata {
    const id = generateAssetId(asset.name)
    return {
        id,
        fileName: asset.name,
        kind: asset.kind,
        width: parseInt(asset.size.split('x')[0]) ?? 300,
        height: parseInt(asset.size.split('x')[1]) ?? 300,
        uploaded: Date.now(),
        title: asset.title,
        year: asset.year,
        material: asset.material,
        tags: asset.tags,
    }
}

const allAssets: LegacyAsset[] = [{
    kind: 'poster',
    name: 'LACMA_2.png',
    title: 'LACMA',
    year: 2022,
    material: 'digital',
    size: '8268x11811',
}, {
    kind: 'drawing',
    name: 'dog.png',
    title: 'Dog',
    year: 2022,
    material: 'ink on paper, color pencil',
    size: '1600x1200',
}, {
    kind: 'poster',
    name: 'in_bruges.png',
    title: 'In Bruges',
    year: 2022,
    material: 'gouache on paper, digital',
    size: '8268x11811',
}, {
    kind: 'poster',
    name: 'contra_spem_spero.png',
    title: 'Contra spem spero!',
    year: 2022,
    material: 'digital',
    size: '8268x11811',
}, {
    kind: 'illustration',
    name: 'officer.png',
    title: 'Officer',
    year: 2022,
    material: 'digital',
    size: '1600x1200',
}, {
    kind: 'poster',
    name: '93rd.jpeg',
    title: '93rd',
    year: 2022,
    material: 'digital',
    size: '905x1280',
}, {
    kind: 'poster',
    name: 'aanda.jpeg',
    title: 'A&A',
    year: 2022,
    material: 'digital',
    size: '853x1280',
    tags: ['secondary'],
}, {
    kind: 'illustration',
    name: 'Anna.png',
    title: 'Anna',
    year: 2020,
    material: 'digital',
    size: '1600x1200',
    tags: ['favorite'],
}, {
    kind: 'poster',
    name: 'body.jpeg',
    title: 'Body',
    year: 2022,
    material: 'digital',
    size: '905x1280',
    tags: ['secondary'],
}, {
    kind: 'poster',
    name: 'bronx_gothic.jpeg',
    title: 'Bronx Gothic',
    year: 2022,
    material: 'colors pensil on paper, digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'darkside.jpeg',
    title: 'Darkside',
    year: 2022,
    material: 'digital',
    size: '896x1280',
    tags: ['secondary'],
}, {
    kind: 'poster',
    name: 'dont_talk.jpeg',
    title: 'Romance',
    year: 2022,
    material: 'diital',
    size: '853x1280',
    tags: ['secondary'],
}, {
    kind: 'painting',
    name: 'Flower_1.png',
    title: 'Flower 1',
    year: 2023,
    material: 'gouache on paper',
    size: '2433x2258',
}, {
    kind: 'painting',
    name: 'Flower_2.png',
    title: 'Flower 2',
    year: 2023,
    material: 'gouache on paper',
    size: '2205x2159',
}, {
    kind: 'painting',
    name: 'Flower_3.png',
    title: 'Flower 3',
    year: 2023,
    material: 'gouache on paper',
    size: '2433x2367',
}, {
    kind: 'painting',
    name: 'Flower_4.png',
    title: 'Flower 4',
    year: 2023,
    material: 'gouache on paper',
    size: '2419x2379',
}, {
    kind: 'painting',
    name: 'Flower_5.png',
    title: 'Flower 5',
    year: 2023,
    material: 'gouache on paper',
    size: '2519x2482',
}, {
    kind: 'painting',
    name: 'Flower_6.png',
    title: 'Flower 6',
    year: 2023,
    material: 'gouache on paper',
    size: '2339x2338',
}, {
    kind: 'painting',
    name: 'Flower_7.png',
    title: 'Flower 7',
    year: 2023,
    material: 'gouache on paper',
    size: '2427x2453',
}, {
    kind: 'painting',
    name: 'Flower_8.png',
    title: 'Flower 8',
    year: 2023,
    material: 'gouache on paper',
    size: '2011x2057',
}, {
    kind: 'painting',
    name: 'Flower_9.png',
    title: 'Flower 9',
    year: 2023,
    material: 'gouache on paper',
    size: '2049x2122',
}, {
    kind: 'illustration',
    name: 'frog.png',
    title: 'Frog',
    year: 2022,
    material: 'digital',
    size: '1600x1200',
}, {
    kind: 'poster',
    name: 'grand_spectacle_de_ballets.jpeg',
    title: 'Grand spectacle de ballets',
    year: 2022,
    material: 'digital',
    size: '896x1280',
},
// {
//     kind: 'illustration',
//     name: 'greek_man.png',
//     title: 'Greek man',
//     year: 2019,
//     material: 'digital',
//     size: '896x1280',
// },
{
    kind: 'poster',
    name: 'estata_la_mano_di_dio.JPG',
    title: 'Estata la mano di dio',
    year: 2022,
    material: 'digital',
    size: '896x1280',
}, {
    kind: 'illustration',
    name: 'eye.jpg',
    title: 'An eye',
    year: 2020,
    material: 'digital',
    size: '2048x2048',
}, {
    kind: 'illustration',
    name: 'happy.png',
    title: 'Happy',
    year: 2022,
    material: 'digital',
    size: '1600x1200',
}, {
    kind: 'illustration',
    name: 'look.jpg',
    title: 'Look',
    year: 2021,
    material: 'digital',
    size: '1000x1000',
    tags: ['favorite'],
}, {
    kind: 'poster',
    name: 'in_decent.jpeg',
    title: 'In decent',
    year: 2022,
    material: 'ink on paper, digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'kyiv.png',
    title: 'Kyiv',
    year: 2022,
    material: 'mixed technique',
    size: '8268x11811',
}, {
    kind: 'poster',
    name: 'LA.jpeg',
    title: 'LA',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'les_miserables.jpeg',
    title: 'Les miserables',
    year: 2022,
    material: 'mixed technique',
    size: '896x1280',
}, {
    kind: 'poster',
    name: 'look.jpeg',
    title: 'Look through',
    year: 2022,
    material: 'digital',
    size: '896x1280',
}, {
    kind: 'poster',
    name: 'love.jpeg',
    title: 'Love (poster)',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'macbeth.jpeg',
    title: 'Macbeth',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'marshall.jpeg',
    title: 'Marshall',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'you.jpeg',
    title: 'YOU',
    year: 2022,
    material: 'digital',
    size: '896x1280',
}, {
    kind: 'poster',
    name: 'me.jpeg',
    title: 'Me',
    year: 2022,
    material: 'digital',
    size: '896x1280',
}, {
    kind: 'poster',
    name: 'monstres.jpeg',
    title: 'Monstres',
    year: 2022,
    material: 'mixed technique',
    size: '896x1280',
}, {
    kind: 'poster',
    name: 'oper.jpeg',
    title: 'Oper',
    year: 2022,
    material: 'mixed technique',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'ophelia.jpeg',
    title: 'Ophelia',
    year: 2022,
    material: 'mixed technique',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'RandJ.jpeg',
    title: 'R&J',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'dakh_dauters.png',
    title: 'Dakh Dauters',
    year: 2018,
    material: 'digital',
    size: '2480x3508',
}, {
    kind: 'poster',
    name: 'DakhaBrakha.png',
    title: 'Dakha Brakha',
    year: 2018,
    material: 'digital',
    size: '2480x3508',
}, {
    kind: 'poster',
    name: 'David_Lynch.png',
    title: 'David Lynch',
    year: 2018,
    material: 'digital',
    size: '2480x3508',
}, {
    kind: 'poster',
    name: 'Romeo_and_Juliet.jpeg',
    title: 'Romeo and Juliet',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'romeoandjuliet.jpeg',
    title: 'Romeo&Juliet',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'SPAM_1.jpeg',
    title: 'SPAM_1',
    year: 2022,
    material: 'marker on paper',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'SPAM_2.jpeg',
    title: 'SPAM_2',
    year: 2022,
    material: 'marker on paper',
    size: '853x1280',
}, {
    kind: 'illustration',
    name: 'pain.jpg',
    title: 'Pain',
    year: 2021,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'rabbit.jpg',
    title: 'Rabbit',
    year: 2020,
    material: 'digital',
    size: '2048x2048',
}, {
    kind: 'illustration',
    name: 'rose.jpg',
    title: 'Rose',
    year: 2023,
    material: 'digital',
    size: '2048x2048',
}, {
    kind: 'poster',
    name: 'shape.jpeg',
    title: 'Shape',
    year: 2022,
    material: 'digital',
    size: '905x1280',
}, {
    kind: 'poster',
    name: 'symbol.jpeg',
    title: 'Symbol',
    year: 2022,
    material: 'digital',
    size: '905x1280',
}, {
    kind: 'poster',
    name: 'the_hour_we_know_nothing.jpeg',
    title: 'The Hour',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'under_wave.jpeg',
    title: 'Under Wave',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'venice_beach.jpeg',
    title: 'Party',
    year: 2022,
    material: 'digital',
    size: '853x1280',
}, {
    kind: 'poster',
    name: 'venice.jpeg',
    title: 'Venice',
    year: 2022,
    material: 'digital',
    size: '905x1280',
}, {
    kind: 'poster',
    name: 'w.jpeg',
    title: 'W',
    year: 2022,
    material: 'digital',
    size: '905x1280',
}, {
    kind: 'poster',
    name: 'war_peace.png',
    title: 'WAR\PEACE',
    year: 2022,
    material: 'digital',
    size: '8268x11811',
    tags: ['secondary'],
}, {
    kind: 'poster',
    name: 'war.jpeg',
    title: 'War',
    year: 2022,
    material: 'digital',
    size: '905x1280',
    tags: ['secondary'],
}, {
    kind: 'poster',
    name: 'when.jpeg',
    title: 'Vingranovsky',
    year: 2022,
    material: 'digital',
    size: '853x1280',
    tags: ['secondary'],
}, {
    kind: 'illustration',
    name: 'walk.png',
    title: 'Walk',
    year: 2022,
    material: 'digital',
    size: '2644x2048',
}, {
    kind: 'illustration',
    name: 'anxiety_thoughts.png',
    title: 'Anxiety Thoughts',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'anxiety_1.png',
    title: 'Anxiety',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'Behavioral_Activation.png',
    title: 'Behavioral Activation',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'tattoo',
    name: 'bird_2.png',
    title: 'Bird #2',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'tattoo',
    name: 'bird.png',
    title: 'Bird',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'book.png',
    title: 'Book',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'bored.png',
    title: 'Bored',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'brain.png',
    title: 'Brain',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'candles.png',
    title: 'Candles',
    year: 2023,
    material: 'digital',
    size: '3024x4032',
}, {
    kind: 'collage',
    name: 'cinema_1.png',
    title: 'Cinema #1',
    year: 2023,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'collage',
    name: 'cinema_2.png',
    title: 'Cinema #2',
    year: 2023,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'collage',
    name: 'cinema_3.png',
    title: 'Cinema #3',
    year: 2023,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'collage',
    name: 'cinema_4.png',
    title: 'Cinema #4',
    year: 2023,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'illustration',
    name: 'clock.png',
    title: 'Clock',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'Cognitive_Restructuring.png',
    title: 'Cognitive Restructuring',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'diarrhea.png',
    title: 'Diarrhea',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'dream.png',
    title: 'Dream',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'Exposure_Therapy.png',
    title: 'Exposure Therapy',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'falling.png',
    title: 'Falling',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'eye.png',
    title: 'Eye',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'feel_good_1.png',
    title: 'Feel good',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'Five_Senses_Grounding_Technique.png',
    title: 'Five senses grounding technique',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'fixed.png',
    title: 'Fixed',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'forty_million.png',
    title: 'Forty million',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'gift.png',
    title: 'Gift',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'headache.png',
    title: 'Headache',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'collage',
    name: 'history_1.png',
    title: 'History',
    year: 2023,
    material: 'digital',
    size: '963x729',
}, {
    kind: 'illustration',
    name: 'line.png',
    title: 'Line',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'lion.png',
    title: 'Lion',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'love.png',
    title: 'Love',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'man.png',
    title: 'Man',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'mess.png',
    title: 'Mess',
    year: 2022,
    material: 'digital',
    size: '2500x2500',
}, {
    kind: 'illustration',
    name: 'Mindful_Eating.png',
    title: 'Mindful eating',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'Mindful_Handwashing.png',
    title: 'Minful handwashing',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'tattoo',
    name: 'moon.png',
    title: 'Moon',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'collage',
    name: '10_hrn.jpg',
    title: '10 Hryvnias',
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'all_cats.jpg',
    title: 'All Cats',
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'au_revoir_mon_cher.jpg',
    title: 'Au revoir,moncher.jpg',
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1400x1925',
}, {
    kind: 'collage',
    name: 'deep.jpg',
    title: 'Deep',
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1400x1018',
    tags: ['favorite'],
}, {
    kind: 'collage',
    name: 'what_to_do_if_children_watch_porn_1.png',
    title: 'What To Do If Children Watch Porn 1',
    year: 2021,
    material: 'digital collage',
    size: '2000x711',
}, {
    kind: 'collage',
    name: 'what_to_do_if_children_watch_porn_2.png',
    title: 'What To Do If Children Watch Porn 2',
    year: 2021,
    material: 'digital collage',
    size: '1300x2000',
    tags: ['favorite'],
}, {
    kind: 'collage',
    name: 'what_to_do_if_children_watch_porn_3.png',
    title: 'What To Do If Children Watch Porn 3',
    year: 2021,
    material: 'digital collage',
    size: '2189x1300',
    tags: ['favorite'],
}, {
    kind: 'collage',
    name: 'find_real_job.jpg',
    title: 'Are you looking for real job?',
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1400x1461',
    tags: ['favorite'],
}, {
    kind: 'collage',
    name: 'hat.jpg',
    title: 'Hat',
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1400x1925',
}, {
    kind: 'collage',
    name: 'is_your_red.jpg',
    title: 'Is your red the same red as mine?',
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1400x1925',
    tags: ['favorite'],
}, {
    kind: 'collage',
    name: 'just_dont_do_it.jpg',
    title: "Just don't do it",
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1277x1314',
    tags: ['favorite'],
}, {
    kind: 'collage',
    name: 'king.jpg',
    title: 'King',
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1400x1018',
    tags: ['favorite'],
}, {
    kind: 'collage',
    name: 'latte.jpg',
    title: 'lAtte-lattE',
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1246x1388',
    tags: ['favorite'],
}, {
    kind: 'collage',
    name: 'look_at_her.jpg',
    title: 'Look at her!',
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1400x1018',
    tags: ['favorite'],
}, {
    kind: 'collage',
    name: 'mcdonalds.jpg',
    title: "McDonald's",
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1400x1018',
    tags: ['favorite'],
}, {
    kind: 'collage',
    name: 'not_so_premium.jpg',
    title: 'Not so premium!',
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1400x1018',
    tags: ['favorite'],
}, {
    kind: 'collage',
    name: 'Peacedove.jpg',
    title: 'Peacedove',
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1400x1018',
    tags: ['favorite'],
}, {
    kind: 'collage',
    name: 'photo.jpg',
    title: 'Photo',
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1400x1925',
    tags: ['favorite'],
}, {
    kind: 'collage',
    name: 'Ryaba_Hen.jpg',
    title: 'Ryaba Hen',
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1400x1018',
    tags: ['favorite'],
}, {
    kind: 'collage',
    name: 'stop.jpg',
    title: 'STOP',
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1400x1682',
    tags: ['favorite'],
}, {
    kind: 'collage',
    name: 'the_human_face.jpg',
    title: 'The human face',
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'have_a_good_one.jpg',
    title: 'Have a Good One!',
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1400x1018',
}, {
    kind: 'collage',
    name: 'Treasure.jpg',
    title: 'Treasure',
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1400x1540',
}, {
    kind: 'collage',
    name: 'what.jpg',
    title: 'What',
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1400x1925',
}, {
    kind: 'collage',
    name: 'ukraine_history_1.png',
    title: 'Ukrainian History #1',
    year: 2022,
    material: 'digital',
    size: '962x729',
    tags: ['favorite'],
}, {
    kind: 'collage',
    name: 'ukraine_history_2.jpg',
    title: 'Ukrainian History #2',
    year: 2022,
    material: 'digital',
    size: '962x729',
}, {
    kind: 'collage',
    name: 'ukraine_history_3.png',
    title: 'Ukrainian History #3',
    year: 2022,
    material: 'digital',
    size: '460x535',
}, {
    kind: 'collage',
    name: 'ukraine_history_4.png',
    title: 'Ukrainian History #4',
    year: 2022,
    material: 'digital',
    size: '542x1230',
}, {
    kind: 'collage',
    name: 'ukraine_history_5.jpg',
    title: 'Ukrainian History #5',
    year: 2022,
    material: 'digital',
    size: '542x1230',
}, {
    kind: 'collage',
    name: 'ukraine_history_6.jpg',
    title: 'Ukrainian History #6',
    year: 2022,
    material: 'digital',
    size: '460x535',
}, {
    kind: 'collage',
    name: 'working_hard.jpg',
    title: 'Working Hard',
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1400x1925',
}, {
    kind: 'collage',
    name: 'We_are_getting_off_at_the_next_stop.jpg',
    title: 'We Are Getting Off At The Next Stop',
    year: 2015,
    material: 'hand-cut magazine images, ink',
    size: '1400x1879',
}, {
    kind: 'painting',
    name: 'after_illness_selfportrait_color.png',
    title: 'After Illness Selfportrait Color.png',
    year: 2023,
    material: 'gouache on paper',
    size: '2386x3339',
    tags: ['selfportrait'],
}, {
    kind: 'painting',
    name: 'after_illness_selfportrait_dark.png',
    title: 'After Illness Selfportrait Dark',
    year: 2023,
    material: 'gouache on paper',
    size: '2228x3078',
    tags: ['selfportrait'],
}, {
    kind: 'illustration',
    name: 'antiseptic.JPG',
    title: 'antiseptic',
    year: 2019,
    material: 'digital',
    size: '2000x1495',
}, {
    kind: 'collage',
    name: 'music_2.png',
    title: 'Music #1',
    year: 2022,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'collage',
    name: 'music_3_2.png',
    title: 'Music #2',
    year: 2022,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'collage',
    name: 'music_4_2.png',
    title: 'Music #3',
    year: 2022,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'collage',
    name: 'music_5.png',
    title: 'Music #4',
    year: 2022,
    material: 'digital',
    size: '3840x2160',
}, {
    kind: 'illustration',
    name: 'namaste.png',
    title: 'Namaste',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'phone.png',
    title: 'Phone',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'pigeon.JPG',
    title: 'Pigeon',
    year: 2022,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'pill.png',
    title: 'Pill',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'pleasant_time.png',
    title: 'Time',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'Problem-Solving_Technique.png',
    title: 'Problem solving technique',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'RAIN_Technique.png',
    title: 'RAIN',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'reminder.png',
    title: 'Reminder',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'routine.png',
    title: 'Routine',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'Self-Monitoring.png',
    title: 'Self Monitoring',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'sleep.png',
    title: 'Sleep',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'smell.png',
    title: 'Smell',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'snakes.png',
    title: 'Snakes',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'star_brain.png',
    title: 'Star Brain',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'star.png',
    title: 'Star',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'stress_1.png',
    title: 'Stress #1',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'stress_2.png',
    title: 'Stress #2',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'summer.png',
    title: 'Summer',
    year: 2022,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'tattoo',
    name: 'sun.png',
    title: 'Sun',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'support.png',
    title: 'Support',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'sweet_dream.png',
    title: 'Sweet',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'thoghts.png',
    title: 'Thoghts',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'Thought_Records.png',
    title: 'Thought records',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'together.png',
    title: 'Together',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'tattoo',
    name: 'tooth.png',
    title: 'Tooth',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'painting',
    name: 'Anton.png',
    title: 'Anton',
    year: 2022,
    material: 'acrylic on paper',
    size: '2568x3504',
    tags: ['favorite'],
}, {
    kind: 'tattoo',
    name: 'Antons_tiger.png',
    title: 'Antons Tiger',
    year: 2022,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'drawing',
    name: 'beach.jpg',
    title: 'Beach',
    year: 2022,
    material: 'marker on paper',
    size: '680x1257',
}, {
    kind: 'drawing',
    name: 'Berlin_museum.JPG',
    title: 'Berlin Museum',
    year: 2022,
    material: 'pensils on paper',
    size: '2767x2767',
}, {
    kind: 'illustration',
    name: 'bite_snake.PNG',
    title: 'Snake bite',
    year: 2022,
    material: 'digital',
    size: '2048x2048',
}, {
    kind: 'drawing',
    name: 'Bucha.JPG',
    title: 'Bucha',
    year: 2022,
    material: 'ink on paper',
    size: '1440x1017',
}, {
    kind: 'drawing',
    name: 'daisies.png',
    title: 'Daisies',
    year: 2022,
    material: 'ink and pensil on paper',
    size: '4032x3024',
}, {
    kind: 'painting',
    name: 'Daryn.png',
    title: 'Daryn',
    year: 2023,
    material: 'acrylic on paper',
    size: '1795x2723',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'dead_dragon.PNG',
    title: 'Dead Dragon',
    year: 2022,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'drawing',
    name: 'elephant.JPG',
    title: 'Elephant',
    year: 2022,
    material: 'ink on paper',
    size: '1440x1777',
}, {
    kind: 'painting',
    name: 'first_working_day_selfportrait.JPG',
    title: 'First Working Day Selfportrait',
    year: 2022,
    material: 'acrylic on paper',
    size: '1212x1176',
    tags: ['selfportrait'],
}, {
    kind: 'painting',
    name: 'sunscreen_selfportrait.png',
    title: 'Sunscreen Selfportrait',
    year: 2022,
    material: 'acrylic on paper',
    size: '2262x2321',
    tags: ['selfportrait'],
}, {
    kind: 'drawing',
    name: 'happy_flower.jpg',
    title: 'Happy Flower',
    year: 2022,
    material: 'ink and pencil on paper',
    size: '2037x2791',
}, {
    kind: 'illustration',
    name: 'i_live_in_Berlin.JPG',
    title: 'I Live In Berlin',
    year: 2022,
    material: 'digital',
    size: '2048x2048',
    tags: ['selfportrait'],
}, {
    kind: 'illustration',
    name: 'insomnia.JPG',
    title: 'Insomnia',
    year: 2020,
    material: 'digital',
    size: '2048x2048',
    tags: ['selfportrait'],
}, {
    kind: 'painting',
    name: 'lemon_tree.png',
    title: 'Lemon Tree',
    year: 2022,
    material: 'acrylic on canvas',
    size: '1422x2176',
}, {
    kind: 'drawing',
    name: 'light_flower.png',
    title: 'Light Flower',
    year: 2023,
    material: 'pastel on paper',
    size: '1991x2468',
}, {
    kind: 'illustration',
    name: 'looking_for.JPG',
    title: 'Looking For',
    year: 2021,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'drawing',
    name: 'lying_down_woman.jpg',
    title: 'Lying Down Woman',
    year: 2021,
    material: 'ink and pastel on paper',
    size: '1215x875',
    tags: ['favorite'],
}, {
    kind: 'tattoo',
    name: 'match.png',
    title: 'Match',
    year: 2022,
    material: 'hand poke',
    size: '2498x3478',
}, {
    kind: 'illustration',
    name: 'micro_green.JPG',
    title: 'Microgreen',
    year: 2020,
    material: 'digital',
    size: '2500x1500',
}, {
    kind: 'painting',
    name: 'mountain_bouquet.png',
    title: 'Mountain Bouquet',
    year: 2023,
    material: 'acrylic on canvas',
    size: '2640x3464',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'my_city.PNG',
    title: 'My City',
    year: 2022,
    material: 'digital',
    size: '1668x1995',
}, {
    kind: 'illustration',
    name: 'need_hugs.JPG',
    title: 'Need Hugs',
    year: 2020,
    material: 'digital',
    size: '2048x2048',
}, {
    kind: 'drawing',
    name: 'nervous_self_portrait.JPG',
    title: 'Nervous Self Portrait',
    year: 2023,
    material: 'charcoal on paper',
    size: '1829x2569',
    tags: ['selfportrait'],
}, {
    kind: 'drawing',
    name: 'parrot.png',
    title: 'Parrot',
    year: 2022,
    material: 'ink on paper',
    size: '3275x2342',
}, {
    kind: 'tattoo',
    name: 'pin_pong.JPG',
    title: 'Pin-Pong',
    year: 2023,
    material: 'hand poke',
    size: '1440x1800',
}, {
    kind: 'drawing',
    name: 'premonition_of_war.png',
    title: 'Premonition of War',
    year: 2022,
    material: 'ink on paper',
    size: '2809x1979',
}, {
    kind: 'tattoo',
    name: 'prickly_flower.png',
    title: 'Prickly Flower',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'painting',
    name: 'red_flower.png',
    title: 'Red Flower',
    year: 2023,
    material: 'gouache on paper',
    size: '2437x3048',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'red_hat_lady.PNG',
    title: 'Red Hat Lady.PNG',
    year: 2023,
    material: 'digital',
    size: '2048x2048',
}, {
    kind: 'illustration',
    name: 'menstruation_1.png',
    title: 'Menstruation 1',
    year: 2020,
    material: 'digital',
    size: '1920x1152',
    tags: ['favorite'],
}, {
    kind: 'tattoo',
    name: 'red_ornament.png',
    title: 'Red Ornament',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'drawing',
    name: 'sad_evening.png',
    title: 'Sad Evening',
    year: 2023,
    material: 'marker on paper',
    size: '2379x3197',
    tags: ['favorite'],
}, {
    kind: 'drawing',
    name: 'sad_selfportrait.PNG',
    title: 'Sad Selfportrait',
    year: 2022,
    material: 'charcoal on paper',
    size: '2890x2268',
    tags: ['selfportrait'],
}, {
    kind: 'painting',
    name: 'self_portrait_color.jpg',
    title: 'Self Portrait in Color',
    year: 2023,
    material: 'acrylic on paper',
    size: '1984x3115',
    tags: ['selfportrait'],
}, {
    kind: 'illustration',
    name: 'self_portrait_on_a_chair.JPG',
    title: 'Self Portrait on A Chair',
    year: 2020,
    material: 'digital',
    size: '2048x2048',
    tags: ['selfportrait'],
}, {

    kind: 'drawing',
    name: 'shark_girl.JPG',
    title: 'Shark Girl',
    year: 2022,
    material: 'ink on paper',
    size: '2391x2988',
    tags: ['favorite'],
}, {
    kind: 'drawing',
    name: 'Sketching in the Museum_room_55B.png',
    title: 'Sketching In the Museum / Dürer',
    year: 2018,
    material: 'marker on paper,digital',
    size: '2800x1976',
    tags: ['favorite'],
}, {
    kind: 'drawing',
    name: 'SPAM_cane.JPG',
    title: 'SPAM Cane',
    year: 2022,
    material: 'pencils on paper',
    size: '3024x3024',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'stand_with_ukraine.PNG',
    title: 'Stand With Ukraine',
    year: 2022,
    material: 'digital',
    size: '2048x2048',
}, {
    kind: 'tattoo',
    name: 'star_collector.png',
    title: 'Star Collector',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'tattoo',
    name: 'star_in_glasses.png',
    title: 'Star in Glasses',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'painting',
    name: 'The_Color_of_Pomegranates.png',
    title: 'The Color of Pomegranates',
    year: 2022,
    material: 'acrylic on paper',
    size: '2395x2841',
    tags: ['favorite'],
}, {
    kind: 'painting',
    name: 'tiger_on_green_with_dots.jpg',
    title: 'Tiger on Green With Dots',
    year: 2021,
    material: 'ink on paper',
    size: '872x1240',
}, {
    kind: 'painting',
    name: 'tiger_on_peace.jpg',
    title: 'Tiger on Peas',
    year: 2021,
    material: 'ink on paper',
    size: '850x1204',
}, {
    kind: 'painting',
    name: 'tiger_on_pink.jpg',
    title: 'Tiger on Pink',
    year: 2021,
    material: 'ink on paper',
    size: '930x1330',
}, {
    kind: 'painting',
    name: 'tiger_on_rose.jpg',
    title: 'Tiger on Rose',
    year: 2021,
    material: 'ink on paper',
    size: '897x1283',
}, {
    kind: 'painting',
    name: 'tiger_on_snow.jpg',
    title: 'Tiger on Snow',
    year: 2021,
    material: 'ink on paper',
    size: '854x1238',
}, {
    kind: 'painting',
    name: 'tiger_on_white.jpg',
    title: 'Tiger on White',
    year: 2021,
    material: 'ink on paper',
    size: '901x1287',
}, {
    kind: 'painting',
    name: 'tiger_on_yellow.jpg',
    title: 'Tiger on Yellow',
    year: 2021,
    material: 'ink on paper',
    size: '864x1249',
}, {
    kind: 'painting',
    name: 'tiger_with_lines.jpg',
    title: 'Tiger With Lines',
    year: 2021,
    material: 'ink on paper',
    size: '892x1264',
}, {
    kind: 'painting',
    name: 'tiger_on_light_green.jpg',
    title: 'Tiger On Green',
    year: 2021,
    material: 'ink and gouche on paper',
    size: '843x1203',
}, {
    kind: 'illustration',
    name: 'Valik.JPG',
    title: 'Valik',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
    tags: ['favorite'],
}, {
    kind: 'tattoo',
    name: 'venice_building.JPG',
    title: 'Venice Building',
    year: 2023,
    material: 'hand_poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'violet_dog.JPG',
    title: 'Violet Dog',
    year: 2021,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'drawing',
    name: 'walking_figure.jpg',
    title: 'Walking Figure',
    year: 2022,
    material: 'ink on paper',
    size: '1806x2580',
    tags: ['favorite'],
}, {
    kind: 'drawing',
    name: 'war_1.png',
    title: 'War 1',
    year: 2022,
    material: 'ink on paper',
    size: '2819x2152',
}, {
    kind: 'drawing',
    name: 'war_2.png',
    title: 'War 2',
    year: 2022,
    material: 'ink on paper',
    size: '3040x2352',
}, {
    kind: 'drawing',
    name: 'war_3.png',
    title: 'War 3',
    year: 2022,
    material: 'ink on paper',
    size: '2935x2182',
}, {
    kind: 'drawing',
    name: 'war_4.png',
    title: 'War 4',
    year: 2022,
    material: 'ink on paper',
    size: '2991x2260',
    tags: ['favorite'],
}, {
    kind: 'painting',
    name: 'wine.png',
    title: 'Wine',
    year: 2023,
    material: 'gouache on paper',
    size: '2278x2925',
}, {
    kind: 'drawing',
    name: 'woman_sculp.JPG',
    title: 'Woman Sculp',
    year: 2022,
    material: 'ink on paper',
    size: '1834x2293',
}, {
    kind: 'illustration',
    name: '5000.png',
    title: '5000',
    year: 2019,
    material: 'digital',
    size: '1840x1008',
}, {
    kind: 'illustration',
    name: 'abuse_1.png',
    title: 'Abuse 1',
    year: 2020,
    material: 'digital',
    size: '1920x1152',
}, {
    kind: 'illustration',
    name: 'abuse_2.png',
    title: 'Abuse 2',
    year: 2020,
    material: 'digital',
    size: '1920x1152',
}, {
    kind: 'illustration',
    name: 'abuse_3.png',
    title: 'Abuse 3',
    year: 2020,
    material: 'digital',
    size: '1920x1152',
}, {
    kind: 'illustration',
    name: 'abuse_4.png',
    title: 'Abuse 4',
    year: 2020,
    material: 'digital',
    size: '1920x1152',
}, {
    kind: 'poster',
    name: 'Aleksievich.png',
    title: 'Aleksievich',
    year: 2018,
    material: 'digital',
    size: '2480x3508',
}, {
    kind: 'illustration',
    name: 'Alex.png',
    title: 'Alex',
    year: 2020,
    material: 'digital',
    size: '1920x2400',
    tags: ['favorite'],
}, {
    kind: 'poster',
    name: 'alphabet.jpg',
    title: 'Alphabet',
    year: 2015,
    material: 'digital',
    size: '1000x1300',
}, {
    kind: 'illustration',
    name: 'all_this_is_weighing_on_me.png',
    title: 'All This Is Weighing On Me.png',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'Ania_with_cat.png',
    title: 'Ania With Cat',
    year: 2019,
    material: 'digital',
    size: '1080x1080',
}, {
    kind: 'illustration',
    name: 'anticipation_of_vacation.png',
    title: 'Anticipation of Vacation',
    year: 2019,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'drawing',
    name: 'Anton_with_nails.png',
    title: 'Anton With Nails',
    year: 2021,
    material: 'digital',
    size: '1000x1000',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'Anton_working.png',
    title: 'Anton Working',
    year: 2020,
    material: 'digital',
    size: '1200x1443',
}, {
    kind: 'illustration',
    name: 'Antons_birthday.png',
    title: 'Antons Birthday',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'Aperole.png',
    title: 'Aperole',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'app.png',
    title: 'App',
    year: 2019,
    material: 'digital',
    size: '1680x840',
}, {
    kind: 'illustration',
    name: 'Argentina.png',
    title: 'Argentina',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'back_pain.png',
    title: 'Back Pain',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'tattoo',
    name: 'bamby.png',
    title: 'Bambi',
    year: 2023,
    material: 'hand poke',
    size: '1440x1800',
}, {
    kind: 'illustration',
    name: 'bdsm.png',
    title: 'BDSM',
    year: 2019,
    material: 'digital',
    size: '2800x1431',
    tags: ['favorite'],
}, {
    kind: 'poster',
    name: 'big_childrens_day.png',
    title: 'Big Childrens Day',
    year: 2018,
    material: 'digital',
    size: '2480x3508',
}, {
    kind: 'poster',
    name: 'Bob_Dylan_night.png',
    title: 'Bob Dylan Night',
    year: 2018,
    material: 'digital',
    size: '2480x3508',
}, {
    kind: 'tattoo',
    name: 'bouquet.png',
    title: 'Bouquet',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'braces.png',
    title: 'Braces',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'tattoo',
    name: 'bread.png',
    title: 'Bread',
    year: 2023,
    material: 'hand poke',
    size: '1126x1800',
}, {
    kind: 'illustration',
    name: 'breakfast.png',
    title: 'Breakfast',
    year: 2018,
    material: 'digital',
    size: '1886x1000',
}, {
    kind: 'illustration',
    name: 'building.png',
    title: 'Building',
    year: 2018,
    material: 'digital',
    size: '1920x960',
}, {
    kind: 'illustration',
    name: 'Bukov_sticker.jpg',
    title: 'Bukov Sticker',
    year: 2018,
    material: 'digital',
    size: '1200x900',
}, {
    kind: 'drawing',
    name: 'Bulka.png',
    title: 'Bulka',
    year: 2021,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'bus_talk.png',
    title: 'Bus Talk',
    year: 2020,
    material: 'digital',
    size: '624x1000',
}, {
    kind: 'illustration',
    name: 'car_fixer.png',
    title: 'Car Fixer',
    year: 2020,
    material: 'digital',
    size: '1200x1200',
}, {
    kind: 'illustration',
    name: 'cat_hotel_1.png',
    title: 'Cat Hotel 1',
    year: 2019,
    material: 'digital',
    size: '1080x1080',
}, {
    kind: 'illustration',
    name: 'cat_hotel_2.png',
    title: 'Cat Hotel 2',
    year: 2019,
    material: 'digital',
    size: '1080x1080',
}, {
    kind: 'illustration',
    name: 'cat_hotel_3.png',
    title: 'Cat Hotel 3',
    year: 2019,
    material: 'digital',
    size: '1080x1080',
}, {
    kind: 'poster',
    name: 'catch_fish_in_your_container.png',
    title: 'Catch Fish in Your Container',
    year: 2021,
    material: 'digital',
    size: '700x1000',
}, {
    kind: 'tattoo',
    name: 'chiken.png',
    title: 'Chiken',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'poster',
    name: 'Childrens_days.png',
    title: 'Childrens Days',
    year: 2019,
    material: 'digital',
    size: '2480x3508',
}, {
    kind: 'illustration',
    name: 'christmas_ball.png',
    title: 'Christmas Ball',
    year: 2021,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'poster',
    name: 'city_communities.jpg',
    title: 'City Communities',
    year: 2018,
    material: 'digital',
    size: '1920x2718',
}, {
    kind: 'poster',
    name: 'city_food_festival.png',
    title: 'City Food Festival',
    year: 2019,
    material: 'digital',
    size: '2480x3508',
}, {
    kind: 'poster',
    name: 'City_Heritage.jpg',
    title: 'City Heritage',
    year: 2018,
    material: 'digital',
    size: '1920x2718',
}, {
    kind: 'poster',
    name: 'City_services.jpg',
    title: 'City Services',
    year: 2018,
    material: 'digital',
    size: '1920x2695',
}, {
    kind: 'illustration',
    name: 'coffee_lover.png',
    title: 'Coffee Lover',
    year: 2019,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'collecting_stuff_1.png',
    title: 'Collecting Stuff 1',
    year: 2018,
    material: 'digital',
    size: '1280x720',
}, {
    kind: 'illustration',
    name: 'collecting_stuff_2.png',
    title: 'Collecting Stuff 2',
    year: 2018,
    material: 'digital',
    size: '1280x720',
}, {
    kind: 'illustration',
    name: 'compliment_about_the_cheeks.png',
    title: 'Compliment About The Cheeks',
    year: 2019,
    material: 'digital',
    size: '1000x1000',
    tags: ['selfportrait'],
}, {
    kind: 'poster',
    name: 'cook_your_song.jpg',
    title: 'Cook Your Song',
    year: 2015,
    material: 'digital',
    size: '1000x1300',
}, {
    kind: 'illustration',
    name: 'couple.png',
    title: 'Couple',
    year: 2021,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'cover_for_Mayak.png',
    title: 'Cover For Mayak',
    year: 2019,
    material: 'digital',
    size: '2800x1036',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'covid_selfportrait.png',
    title: 'Covid Selfportrait',
    year: 2020,
    material: 'digital',
    size: '1400x1400',
    tags: ['selfportrait'],
}, {
    kind: 'poster',
    name: 'donor_day.png',
    title: 'Donor day',
    year: 2020,
    material: 'digital',
    size: '700x1000',
    tags: ['secondary'],
}, {
    kind: 'illustration',
    name: 'doula_1.png',
    title: 'Doula 1',
    year: 2019,
    material: 'digital',
    size: '1280x720',
}, {
    kind: 'illustration',
    name: 'doula_2.png',
    title: 'Doula 2',
    year: 2019,
    material: 'digital',
    size: '1280x720',
}, {
    kind: 'illustration',
    name: 'ego.png',
    title: 'Ego',
    year: 2021,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'poster',
    name: 'Evening_of_Dmytro_Bykov_1.png',
    title: 'Evening Of Dmytro_Bykov 1',
    year: 2018,
    material: 'digital',
    size: '2800x3964',
}, {
    kind: 'poster',
    name: 'Evening_of_Dmytro_Bykov_2.png',
    title: 'Evening Of Dmytro Bykov 2',
    year: 2018,
    material: 'digital',
    size: '1200x1699',
}, {
    kind: 'poster',
    name: 'Evening_of_Dmytro_Bykov_3.png',
    title: 'Evening Of Dmytro Bykov 3',
    year: 2018,
    material: 'digital',
    size: '1200x1699',
}, {
    kind: 'tattoo',
    name: 'eye_star.png',
    title: 'Eye Star',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'face.png',
    title: 'Face',
    year: 2021,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'fall_sadness.png',
    title: 'Fall Sadness',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'fears_when_you_left_home.png',
    title: 'Fears When You Left Home',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'feel_sexy.png',
    title: 'Feel Sexy',
    year: 2019,
    material: 'digital',
    size: '1000x1000',
    tags: ['selfportrait'],
}, {
    kind: 'illustration',
    name: 'filmsection_of_the_green_theater.png',
    title: 'Filmsection Of The Green Theater',
    year: 2019,
    material: 'digital',
    size: '851x315',
}, {
    kind: 'tattoo',
    name: 'finger_tattoo_2.png',
    title: 'Finger Tattoo 2',
    year: 2023,
    material: 'hand poke',
    size: '1440x1800',
}, {
    kind: 'tattoo',
    name: 'fingers_1.png',
    title: 'Finger Tattoo 1',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'poster',
    name: 'food_festival.png',
    title: 'Food Festival',
    year: 2018,
    material: 'digital',
    size: '2480x3508',
    tags: ['secondary'],
}, {
    kind: 'collage',
    name: 'foot_wear.png',
    title: 'Foot Wear',
    year: 2019,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'gay_love_2.png',
    title: 'Gay Love 2',
    year: 2019,
    material: 'digital',
    size: '1600x600',
}, {
    kind: 'illustration',
    name: 'gay_love.gif',
    title: 'Gay Love 1',
    year: 2019,
    material: 'digital',
    size: '1600x600',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'gonchara.png',
    title: 'Gonchara',
    year: 2021,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'collage',
    name: 'Green_Theatre_hiring_1.png',
    title: 'Green Theatre Hiring 1',
    year: 2018,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'collage',
    name: 'Green_Theatre_hiring_2.png',
    title: 'Green Theatre Hiring 2',
    year: 2019,
    material: 'digital',
    size: '1200x1201',
}, {
    kind: 'poster',
    name: 'Green_Theatre_opening.png',
    title: 'Green Theatre Opening',
    year: 2019,
    material: 'digtal',
    size: '2480x3508',
}, {
    kind: 'illustration',
    name: 'grocery_store.png',
    title: 'Grocery Store',
    year: 2019,
    material: 'digital',
    size: '1600x1000',
}, {
    kind: 'illustration',
    name: 'harm.png',
    title: 'Harm',
    year: 2020,
    material: 'digtal',
    size: '1200x1200',
}, {
    kind: 'tattoo',
    name: 'have_a_day.png',
    title: 'Have A Day',
    year: 2023,
    material: 'hand poke',
    size: '2748x4032',
}, {
    kind: 'illustration',
    name: 'helplessness.png',
    title: 'Helplessness',
    year: 2021,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'hiring.png',
    title: 'Hiring',
    year: 2019,
    material: 'digital',
    size: '1065x628',
}, {
    kind: 'illustration',
    name: 'home_pot.png',
    title: 'Home Pot',
    year: 2019,
    material: 'digital',
    size: '1000x1000',
    tags: ['selfportrait'],
}, {
    kind: 'illustration',
    name: 'how_to_choose_a_therapist_1.png',
    title: 'How To Choose A Therapist 1',
    year: 2020,
    material: 'digital',
    size: '1600x1000',
}, {
    kind: 'illustration',
    name: 'how_to_choose_a_therapist_2.png',
    title: 'How To Choose A Therapist 2',
    year: 2020,
    material: 'digital',
    size: '1600x1000',
}, {
    kind: 'illustration',
    name: 'I_cant.png',
    title: 'I Can"t',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'it_guy_1.png',
    title: 'IT Guy 1',
    year: 2019,
    material: 'digital',
    size: '1840x1008',
}, {
    kind: 'illustration',
    name: 'it_guy_2.png',
    title: 'IT Guy 2',
    year: 2019,
    material: 'digital',
    size: '1840x1008',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'it_guy_3.png',
    title: 'IT Guy 3',
    year: 2019,
    material: 'digital',
    size: '1840x1008',
}, {
    kind: 'poster',
    name: 'Jarmusch.jpg',
    title: 'Jarmusch',
    year: 2019,
    material: 'digital',
    size: '2800x2664',
}, {
    kind: 'poster',
    name: 'KISFF.png',
    title: 'KISFF',
    year: 2019,
    material: 'digital',
    size: '2480x3508',
}, {
    kind: 'illustration',
    name: 'Lady_portrait.png',
    title: 'Lady Portrait',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'tattoo',
    name: 'lamp.png',
    title: 'Lamp',
    year: 2023,
    material: 'hand poke',
    size: '2314x3545',
}, {
    kind: 'tattoo',
    name: 'locket.png',
    title: 'Locket',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'long_selfportrait.png',
    title: 'Long Selfportrait',
    year: 2020,
    material: 'digital',
    size: '2800x359',
    tags: ['selfportrait'],
}, {
    kind: 'illustration',
    name: 'looking_for_IT.png',
    title: 'Looking For IT',
    year: 2019,
    material: 'digital',
    size: '1680x920',
}, {
    kind: 'illustration',
    name: 'Mari_with_dog.png',
    title: 'Mari With Dog',
    year: 2019,
    material: 'digital',
    size: '1000x1000',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'Mari.png',
    title: 'Mari',
    year: 2020,
    material: 'digital',
    size: '1200x1200',
}, {
    kind: 'illustration',
    name: 'Masha.png',
    title: 'Masha',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'Ciao_menstruation.png',
    title: 'Ciao Menstruation.',
    year: 2021,
    material: 'digital',
    size: '1000x1000',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'menstruation_2.png',
    title: 'Menstruation 2',
    year: 2020,
    material: 'digital',
    size: '1920x1152',
}, {
    kind: 'illustration',
    name: 'menstruation_3.png',
    title: 'Menstruation 3',
    year: 2020,
    material: 'digital',
    size: '1920x1176',
}, {
    kind: 'illustration',
    name: 'menstruation_4.png',
    title: 'Menstruation 4',
    year: 2020,
    material: 'digital',
    size: '1920x1176',
}, {
    kind: 'illustration',
    name: 'MeRT.png',
    title: 'MeRT',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'poster',
    name: 'micele_shur.png',
    title: 'Michael Shur',
    year: 2019,
    material: 'digital',
    size: '2480x3508',
}, {
    kind: 'illustration',
    name: 'mistakes.png',
    title: 'Mistakes',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'Morning.png',
    title: 'Morning',
    year: 2019,
    material: 'digital',
    size: '2480x3508',
    tags: ['selfportrait'],
}, {
    kind: 'poster',
    name: 'movie_classics_on_Mondays_1.png',
    title: 'Movie classics On Mondays 1',
    year: 2019,
    material: 'digital',
    size: '1200x1697',
}, {
    kind: 'poster',
    name: 'movie_classics_on_Mondays_2.png',
    title: 'Movie classics On Mondays 2',
    year: 2019,
    material: 'digital',
    size: '1200x1697',
}, {
    kind: 'poster',
    name: 'movie_classics_on_Mondays_3.png',
    title: 'Movie classics On Mondays 3',
    year: 2019,
    material: 'digital',
    size: '1200x1697',
}, {
    kind: 'poster',
    name: 'movie_concert.png',
    title: 'Movie Concert',
    year: 2019,
    material: 'digital',
    size: '2480x3580',
}, {
    kind: 'poster',
    name: 'Muratova_cinema.jpg',
    title: 'Muratova Cinema',
    year: 2020,
    material: 'digital',
    size: '1200x1699',
}, {
    kind: 'illustration',
    name: 'muratova.png',
    title: 'Muratova',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'my_fertility.png',
    title: 'My Fertility',
    year: 2019,
    material: 'digital',
    size: '1000x1000',
    tags: ['selfportrait'],
}, {
    kind: 'illustration',
    name: 'new_year_tree.png',
    title: 'New Year Tree',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'Odesa_district_1.jpg',
    title: 'Odesa District 1',
    year: 2019,
    material: 'digital',
    size: '1600x1000',
}, {
    kind: 'illustration',
    name: 'Odesa_district_2.jpg',
    title: 'Odesa District 2',
    year: 2019,
    material: 'digital',
    size: '1600x1000',
}, {
    kind: 'illustration',
    name: 'Odesa_with_friends.png',
    title: 'Odesa With Friends',
    year: 2019,
    material: 'digital',
    size: '1000x1000'
}, {
    kind: 'illustration',
    name: 'Oksana.png',
    title: 'Oksana',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'on_the_grass.png',
    title: 'On The Grass',
    year: 2019,
    material: 'digital',
    size: '1000x1000',
    tags: ['selfportrait'],
}, {
    kind: 'illustration',
    name: 'on_the_mountain.png',
    title: 'On The Mountain',
    year: 2019,
    material: 'digital',
    size: '1000x1000',
    tags: ['selfportrait'],
}, {
    kind: 'illustration',
    name: 'online_order.png',
    title: 'Online Order',
    year: 2020,
    material: 'digital',
    size: '1400x1400',
}, {
    kind: 'illustration',
    name: 'Oops.png',
    title: 'Oops',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'oppressed.png',
    title: 'Oppressed',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'organ_donation_1.png',
    title: 'Organ Donation 1',
    year: 2019,
    material: 'digital',
    size: '2800x1979',
}, {
    kind: 'illustration',
    name: 'organ_donation_2.png',
    title: 'Organ Donation 2',
    year: 2019,
    material: 'digital',
    size: '2800x1979',
}, {
    kind: 'illustration',
    name: 'overwhelmed.png',
    title: 'overwhelmed.png',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'own_garden_in_Green_theatre.png',
    title: 'Own Garden In Green Theatre',
    year: 2019,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'collage',
    name: 'parenthood_1.jpg',
    title: 'Parenthood 1',
    year: 2019,
    material: 'digital',
    size: '1600x775',
    tags: ['favorite'],
}, {
    kind: 'collage',
    name: 'parenthood_2.jpg',
    title: 'Parenthood 2',
    year: 2019,
    material: 'digital',
    size: '1600x775',
    tags: ['favorite'],
}, {
    kind: 'collage',
    name: 'parenthood_3.jpg',
    title: 'Parenthood 3',
    year: 2019,
    material: 'digital',
    size: '1600x775',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'psychotherapy.png',
    title: 'Psychotherapy',
    year: 2021,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'poster',
    name: 'public_spaces.jpg',
    title: 'Public Spaces',
    year: 2018,
    material: 'digital',
    size: '1920x2718',
}, {
    kind: 'illustration',
    name: 'red_eyes.png',
    title: 'Red Eyes',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'red_thread.png',
    title: 'Red thread',
    year: 2021,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'sadness.png',
    title: 'Sadness',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'saving_energy.png',
    title: 'Saving Energy',
    year: 2020,
    material: 'digital',
    size: '1600x1000',
}, {
    kind: 'illustration',
    name: 'school_bullying_1.png',
    title: 'School Bullying 1',
    year: 2019,
    material: 'digtal',
    size: '2800x1979',
}, {
    kind: 'illustration',
    name: 'school_bullying_2.png',
    title: 'School Bullying 2',
    year: 2019,
    material: 'digtal',
    size: '2480x3508',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'self_employed.png',
    title: 'Self-Employed',
    year: 2020,
    material: 'digital',
    size: '1920x1176',
}, {
    kind: 'illustration',
    name: 'self_love.png',
    title: 'Self Love',
    year: 2019,
    material: 'digital',
    size: '2800x1979',
}, {
    kind: 'illustration',
    name: 'sexy_cat.png',
    title: 'Sexy Cat',
    year: 2020,
    material: 'dgital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'silent_french_girl.png',
    title: 'Silent French Girl',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'drawing',
    name: 'Sketching in the Museum_Judit.png',
    title: 'Sketching In The Museum. Judit',
    year: 2018,
    material: 'marker on paper, digital',
    size: '2800x1754',
}, {
    kind: 'drawing',
    name: 'Sketching in the Museum_Pablo_de_Valladolid.png',
    title: 'Sketching In The Museum. Pablo de Valladolid',
    year: 2018,
    material: 'marker on paper,digital',
    size: '2800x1976',
    tags: ['favorite'],
}, {
    kind: 'drawing',
    name: 'Sketching in the Museum_room_19.png',
    title: 'Sketching In the Museum / Tiepolo',
    year: 2018,
    material: 'marker on paper,digital',
    size: '2800x1976',
}, {
    kind: 'drawing',
    name: 'Sketching in the Museum_room_49.png',
    title: 'Sketching In the Museum / Raphael',
    year: 2018,
    material: 'marker on paper,digital',
    size: '2800x1754',
    tags: ['favorite'],
}, {
    kind: 'drawing',
    name: 'Sketching in the Museum_room_55.png',
    title: 'Sketching In the Museum / Mary Tudor',
    year: 2018,
    material: 'marker on paper,digital',
    size: '2800x1754',
}, {
    kind: 'drawing',
    name: 'Sketching in the Museum.png',
    title: 'Sketching In the Museum',
    year: 2018,
    material: 'marker on paper,digital',
    size: '2800x1754',
}, {
    kind: 'illustration',
    name: 'skin_story.jpg',
    title: 'Skin Story',
    year: 2018,
    material: 'digital',
    size: '2480x1748',
}, {
    kind: 'poster',
    name: 'Smirnov.png',
    title: 'Smirnov',
    year: 2018,
    material: 'digital',
    size: '2480x3508',
}, {
    kind: 'illustration',
    name: 'social_media.png',
    title: 'Social Media',
    year: 2020,
    material: 'digital',
    size: '1920x966',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'still_life_with_white_vase.png',
    title: 'Still Life With White Vase',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'supportive_Mari.png',
    title: 'Supportive Mari',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'tattoo',
    name: 'table_tennis.png',
    title: 'Table Tennis',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'illustration',
    name: 'tan.png',
    title: 'Tan',
    year: 2019,
    material: 'digital',
    size: '1000x1000',
    tags: ['selfportrait'],
}, {
    kind: 'illustration',
    name: 'terrible_headache.png',
    title: 'Terrible Headache',
    year: 2020,
    material: 'digital',
    size: '1400x1400',
}, {
    kind: 'illustration',
    name: 'The_Botanical_garden_at_Green_Theatre.png',
    title: 'The Botanical Garden At Green Theatre',
    year: 2019,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'tired_of_menstruation.png',
    title: 'Tired Of Menstruation',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'illustration',
    name: 'trojan_war.png',
    title: 'Trojan War',
    year: 2020,
    material: 'digital',
    size: '1000x1000',
}, {
    kind: 'tattoo',
    name: 'tt.png',
    title: 'TT',
    year: 2023,
    material: 'hand poke',
    size: '1440x1800',
}, {
    kind: 'poster',
    name: 'Urban_Ecology.jpg',
    title: 'Urban Ecology',
    year: 2018,
    material: 'digital',
    size: '1920x2715',
}, {
    kind: 'illustration',
    name: 'vacation.png',
    title: 'Vacation',
    year: 2018,
    material: 'digital',
    size: '1200x1200',
    tags: ['selfportrait'],
}, {
    kind: 'illustration',
    name: 'Valik_and_badminton.png',
    title: 'Valik And Badminton',
    year: 2020,
    material: 'digital',
    size: '1920x1920',
}, {
    kind: 'illustration',
    name: 'vsi_svoi_1.png',
    title: 'Vsi Svoi 1',
    year: 2018,
    material: 'digital',
    size: '2000x1414',
}, {
    kind: 'illustration',
    name: 'Vsi_svoi_2.png',
    title: 'Vsi Svoi 2',
    year: 2018,
    material: 'digital',
    size: '2000x1414',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'Vsi_svoi_3.png',
    title: 'Vsi Svoi 3',
    year: 2018,
    material: 'digital',
    size: '2000x1414',
}, {
    kind: 'illustration',
    name: 'washing-up.png',
    title: 'Washing-up',
    year: 2020,
    material: 'digital',
    size: '1920x1920',
}, {
    kind: 'illustration',
    name: 'way_to_home.png',
    title: 'Way To Home',
    year: 2019,
    material: 'digital',
    size: '1920x1918',
}, {
    kind: 'poster',
    name: 'what_will_happen_to_museums.png',
    title: 'What Will Happen To Museums',
    year: 2019,
    material: 'digital',
    size: '2480x3508',
}, {
    kind: 'tattoo',
    name: 'whisk.png',
    title: 'Whisk',
    year: 2023,
    material: 'hand poke',
    size: '3024x4032',
}, {
    kind: 'poster',
    name: 'workshop.png',
    title: 'Workshop',
    year: 2019,
    material: 'digital',
    size: '1200x1200',
}, {
    kind: 'illustration',
    name: 'cat_calling_1.png',
    title: 'Cat Calling 1',
    year: 2021,
    material: 'digital',
    size: '2500x1500',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'cat_calling_2.png',
    title: 'Cat Calling 2',
    year: 2021,
    material: 'digital',
    size: '2500x1500',
}, {
    kind: 'illustration',
    name: 'cat_calling_3.png',
    title: 'Cat Calling 3',
    year: 2021,
    material: 'digital',
    size: '1500x1761',
}, {
    kind: 'illustration',
    name: 'eating_disorders_1.png',
    title: 'Eating Disorders 1',
    year: 2021,
    material: 'digital',
    size: '2500x1500',
}, {
    kind: 'illustration',
    name: 'eating_disorders_2.png',
    title: 'Eating Disorders 2',
    year: 2021,
    material: 'digital',
    size: '2500x1500',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'eating_disorders_3.png',
    title: 'Eating Disorders 3',
    year: 2021,
    material: 'digital',
    size: '2500x1500',
}, {
    kind: 'illustration',
    name: 'eating_disorders_4.png',
    title: 'Eating Disorders 4',
    year: 2021,
    material: 'digital',
    size: '2500x1500',
}, {
    kind: 'illustration',
    name: 'heroes_engineers_1.png',
    title: 'Heroes Engineers 1',
    year: 2021,
    material: 'digital',
    size: '2500x1500',
}, {
    kind: 'illustration',
    name: 'heroes_engineers_2.png',
    title: 'Heroes Engineers 2',
    year: 2021,
    material: 'digital',
    size: '2500x1500',
}, {
    kind: 'illustration',
    name: 'heroes_engineers_3.png',
    title: 'Heroes Engineers 3',
    year: 2021,
    material: 'digital',
    size: '2500x1500',
}, {
    kind: 'illustration',
    name: 'mood.png',
    title: 'Mood',
    year: 2023,
    material: 'digital',
    size: '1644x1644',
}, {
    kind: 'illustration',
    name: 'heroes_engineers_4.png',
    title: 'Heroes Engineers 4',
    year: 2021,
    material: 'digital',
    size: '2500x1500',
}, {
    kind: 'illustration',
    name: 'Illness_anxiety_disorder_1.png',
    title: 'Illness Anxiety Disorder 1',
    year: 2021,
    material: 'digital collage',
    size: '2500x1500',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'Illness_anxiety_disorder_2.png',
    title: 'Illness Anxiety Disorder 2',
    year: 2021,
    material: 'digital collage',
    size: '2500x1500',
}, {
    kind: 'illustration',
    name: 'Illness_anxiety_disorder_3.png',
    title: 'Illness Anxiety Disorder 3',
    year: 2021,
    material: 'digital collage',
    size: '2500x1500',
}, {
    kind: 'illustration',
    name: 'Illness_anxiety_disorder_4.png',
    title: 'Illness Anxiety Disorder 4',
    year: 2021,
    material: 'digital collage',
    size: '2500x1500',
}, {
    kind: 'illustration',
    name: 'sperm_donation_1.png',
    title: 'Sperm Donation 1',
    year: 2021,
    material: 'digital',
    size: '2500x1500',
}, {
    kind: 'illustration',
    name: 'sperm_donation_2.png',
    title: 'Sperm Donation 2',
    year: 2021,
    material: 'digital',
    size: '2500x1500',
}, {
    kind: 'illustration',
    name: 'sperm_donation_3.png',
    title: 'Sperm Donation 3',
    year: 2021,
    material: 'digital',
    size: '2500x1500',
}, {
    kind: 'illustration',
    name: 'toxic_masculinity_1.png',
    title: 'Toxic Masculinity 1',
    year: 2021,
    material: 'digital',
    size: '2500x1500',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'toxic_masculinity_2.png',
    title: 'Toxic Masculinity 2',
    year: 2021,
    material: 'digital',
    size: '2500x1500',
    tags: ['favorite'],
}, {
    kind: 'illustration',
    name: 'Walking_Meditation.PNG',
    title: 'Walking Meditation',
    year: 2023,
    material: 'digital',
    size: '1656x1318',
}, {
    kind: 'illustration',
    name: 'cat_sitting.JPG',
    title: 'Cat Sitting',
    year: 2019,
    material: 'digital',
    size: '1679x1667',
    tags: ['selfportrait'],
}, {
    kind: 'drawing',
    name: 'running_away.JPG',
    title: 'Running Away',
    year: 2022,
    material: 'ink and pensil on paper',
    size: '1440x999',
    tags: ['favorite'],
}, {
    kind: 'drawing',
    name: 'Gogen_girl.jpg',
    title: 'Gogen Girl',
    year: 2022,
    material: 'pencils on paper',
    size: '2889x2889',
    tags: ['favorite'],
}, {
    kind: 'drawing',
    name: 'blue_man.png',
    title: 'Blue Man',
    year: 2021,
    material: 'ink on paper',
    size: '3122x2206',
}]